import { useEffect, useMemo } from "react";

interface ScholarGeneratorProps {
    setPrompt: (newPrompt: string[]) => void;
    scholarType: string;
}

export default function ScholarGenerator({
    scholarType,
    setPrompt,
}: ScholarGeneratorProps) {


    // clean up vocab and add more interesting words.. 
    const vocabDefinitions: string[] = [
        "Alchemy; the medieval forerunner of chemistry, focused on transforming substances like lead into gold.",
        "Aardvark; a nocturnal mammal from Africa with a long snout for eating ants and termites.",
        "Abdicate; to formally give up a position of power or responsibility.",
        "Aberration; a departure from what is normal or expected, typically one that is unwelcome.",
        "Abhor; to regard with disgust and hatred.",
        "Absolve; to free someone from blame, guilt, or responsibility.",
        "Accentuate; to make something more noticeable or prominent.",
        "Acumen; the ability to make good judgments and quick decisions, typically in a particular domain.",
        "Admonish; to warn or reprimand someone firmly.",
        "Aesthetic; concerned with beauty or the appreciation of beauty.",
        "Affable; friendly, good-natured, or easy to talk to.",
        "Aghast; filled with horror or shock.",
        "Altruism; the belief in or practice of selfless concern for the well-being of others.",
        "Amalgamate; to combine or unite to form one organization or structure.",
        "Ambiguous; open to more than one interpretation, having a double meaning.",
        "Ameliorate; to make something bad or unsatisfactory better.",
        "Amicable; having a spirit of friendliness, without serious disagreement or rancor.",
        "Anachronism; a thing belonging to a period other than that in which it exists, especially something old-fashioned.",
        "Anathema; something or someone that one vehemently dislikes.",
        "Antithesis; a person or thing that is the direct opposite of someone or something else.",
        "Aplomb; self-confidence or assurance, especially when in a demanding situation.",
        "Apocryphal; of doubtful authenticity, although widely circulated as being true.",
        "Apprehensive; anxious or fearful that something bad or unpleasant will happen.",
        "Arbitrary; based on random choice or personal whim, rather than any reason or system.",
        "Ardent; enthusiastic or passionate.",
        "Articulate; having or showing the ability to speak fluently and coherently.",
        "Ascertain; to find something out for certain, to make sure of.",
        "Astute; having or showing an ability to accurately assess situations or people and turn this to one’s advantage.",
        "Asylum; the protection granted by a nation to someone who has left their native country as a political refugee.",
        "Atrophy; the gradual decline in effectiveness or vigor due to underuse or neglect.",
        "Audacious; showing a willingness to take surprisingly bold risks.",
        "Auspicious; conducive to success, favorable.",
        "Autonomy; the right or condition of self-government.",
        "Aversion; a strong dislike or disinclination.",
        "Abyss; a deep or seemingly bottomless chasm.",
        "Accolade; an award or privilege granted as a special honor.",
        "Acerbic; sharp and forthright, especially in style of speaking or writing.",
        "Acquiesce; to accept something reluctantly but without protest.",
        "Acrimony; bitterness or ill feeling.",
        "Adroit; clever or skillful in using the hands or mind.",
        "Advocate; a person who publicly supports or recommends a particular cause or policy.",
        "Aestheticism; the appreciation of beauty or art.",
        "Aggrandize; to increase the power, status, or wealth of.",
        "Alacrity; brisk and cheerful readiness.",
        "Alienate; to cause someone to feel isolated or estranged.",
        "Allay; to diminish or put at rest a fear, suspicion, or worry.",
        "Allegory; a story, poem, or picture that can be interpreted to reveal a hidden meaning, typically a moral or political one.",
        "Allude; to suggest or call attention to indirectly.",
        "Aloof; not friendly or forthcoming, cool and distant.",
        "Amorphous; without a clearly defined shape or form.",
        "Anarchy; a state of disorder due to absence or nonrecognition of authority.",
        "Anecdote; a short and amusing or interesting story about a real incident or person.",
        "Animosity; strong hostility.",
        "Annex; to add as an extra or subordinate part, especially to a document.",
        "Anomaly; something that deviates from what is standard, normal, or expected.",
        "Antecedent; a thing or event that existed before or logically precedes another.",
        "Antipathy; a deep-seated feeling of dislike.",
        "Apex; the top or highest part of something, especially one forming a point.",
        "Apocalypse; the complete final destruction of the world, as described in the biblical book of Revelation.",
        "Benevolent; well-meaning and kindly.",
        "Belligerent; hostile and aggressive.",
        "Banal; so lacking in originality as to be obvious and boring.",
        "Beguile; to charm or enchant someone, often in a deceptive way.",
        "Blatant; done openly and unashamedly, very obvious.",
        "Brevity; concise and exact use of words in writing or speech.",
        "Boisterous; noisy, energetic, and cheerful.",
        "Bolster; to support or strengthen.",
        "Benevolent; showing or motivated by sympathy and understanding.",
        "Bifurcate; to divide into two branches or forks.",
        "Blithe; showing a casual and cheerful indifference considered to be callous or improper.",
        "Burgeon; to begin to grow or increase rapidly, flourish.",
        "Benevolence; the quality of being well-meaning and kind.",
        "Behemoth; a huge or monstrous creature.",
        "Blasphemy; the act of speaking sacrilegiously about God or sacred things.",
        "Belligerence; aggressive or warlike behavior.",
        "Bountiful; large in quantity, abundant.",
        "Blunder; a stupid or careless mistake.",
        "Buoyant; able or apt to stay afloat or rise to the top of a liquid or gas.",
        "Bewilder; to cause someone to become perplexed and confused.",
        "Banish; to send someone away from a country or place as an official punishment.",
        "Beseech; to ask someone urgently and fervently to do something.",
        "Benevolence; the quality of being well-meaning, kindness.",
        "Brusque; abrupt or offhand in speech or manner.",
        "Brawn; physical strength in contrast to intelligence.",
        "Bellicose; demonstrating aggression and willingness to fight.",
        "Beneficiary; a person who derives advantage from something, especially a trust, will, or life insurance policy.",
        "Bohemian; socially unconventional in an artistic way.",
        "Brazen; bold and without shame.",
        "Burlesque; a literary or dramatic work that seeks to ridicule by means of grotesque exaggeration or comic imitation.",
        "Bucolic; relating to the pleasant aspects of the countryside and country life.",
        "Beseech; to ask someone urgently and fervently to do or give something.",
        "Bifurcation; the division of something into two branches or parts.",
        "Blithely; in a way that shows a casual and cheerful indifference considered to be callous or improper.",
        "Bane; a cause of great distress or annoyance.",
        "Bard; a poet, traditionally one reciting epics and associated with a particular oral tradition.",
        "Bastion; a projecting part of a fortification built at an angle to the line of a wall, so as to allow defensive fire in several directions.",
        "Befuddle; to make someone unable to think clearly.",
        "Bequeath; to leave a personal estate or one's body to a person or other beneficiary by a will.",
        "Bereft; deprived of or lacking something, especially a nonmaterial asset.",
        "Blanch; to make white or pale by extracting color.",
        "Bludgeon; a thick stick with a heavy end, used as a weapon.",
        "Bravado; a bold manner or a show of boldness intended to impress or intimidate.",
        "Braggart; a person who boasts about achievements or possessions.",
        "Brevity; concise and exact use of words in writing or speech.",
        "Broach; to raise a sensitive or difficult subject for discussion.",
        "Bursar; a person who manages the financial affairs of a college or university.",
        "Byzantine; excessively complicated, and typically involving a great deal of administrative detail.",
        "Cacophony; a harsh, discordant mixture of sounds.",
        "Cajole; to persuade someone to do something by sustained coaxing or flattery.",
        "Callous; showing or having an insensitive and cruel disregard for others.",
        "Camaraderie; mutual trust and friendship among people who spend a lot of time together.",
        "Candor; the quality of being open and honest in expression, frankness.",
        "Capricious; given to sudden and unaccountable changes of mood or behavior.",
        "Catharsis; the process of releasing, and thereby providing relief from, strong or repressed emotions.",
        "Censure; express severe disapproval of someone or something, typically in a formal statement.",
        "Chagrin; distress or embarrassment at having failed or been humiliated.",
        "Chicanery; the use of trickery to achieve a political, financial, or legal purpose.",
        "Circumvent; find a way around an obstacle.",
        "Clandestine; kept secret or done secretively, especially because illicit.",
        "Clemency; mercy, lenience.",
        "Coerce; persuade an unwilling person to do something by using force or threats.",
        "Cogent; clear, logical, and convincing.",
        "Commensurate; corresponding in size or degree, in proportion.",
        "Compassion; sympathetic pity and concern for the sufferings or misfortunes of others.",
        "Conflagration; an extensive fire that destroys a great deal of land or property.",
        "Conundrum; a confusing and difficult problem or question.",
        "Convivial; friendly, lively, and enjoyable.",
        "Copious; abundant in supply or quantity.",
        "Corroborate; confirm or give support to a statement, theory, or finding.",
        "Coterie; a small group of people with shared interests or tastes, especially one that is exclusive of other people.",
        "Culminate; reach a climax or point of highest development.",
        "Cursory; hasty and therefore not thorough or detailed.",
        "Curtail; reduce in extent or quantity, impose a restriction on.",
        "Cryptic; having a meaning that is mysterious or obscure.",
        "Cynical; believing that people are motivated by self-interest, distrustful of human sincerity or integrity.",
        "Cacophony; a harsh, discordant mixture of sounds.",
        "Calamity; an event causing great and often sudden damage or distress, a disaster.",
        "Capitulate; cease to resist an opponent or an unwelcome demand, surrender.",
        "Caricature; a picture, description, or imitation of a person in which certain striking characteristics are exaggerated in order to create a comic or grotesque effect.",
        "Castigate; reprimand someone severely.",
        "Catalyst; a substance that increases the rate of a chemical reaction without itself undergoing any permanent chemical change.",
        "Caveat; a warning or proviso of specific stipulations, conditions, or limitations.",
        "Chastise; rebuke or reprimand severely.",
        "Chivalrous; courteous and gallant, especially towards women.",
        "Clairvoyant; a person who claims to have a supernatural ability to perceive events in the future or beyond normal sensory contact.",
        "Cognizant; having knowledge or being aware of.",
        "Commiserate; express or feel sympathy or pity, sympathize.",
        "Complacent; showing smug or uncritical satisfaction with oneself or one's achievements.",
        "Compliant; inclined to agree with others or obey rules, especially to an excessive degree.",
        "Conciliatory; intended or likely to placate or pacify.",
        "Conspicuous; standing out so as to be clearly visible.",
        "Contemptuous; showing contempt, scornful.",
        "Contingent; subject to chance.",
        "Contrite; feeling or expressing remorse or penitence, affected by guilt.",
        "Convoluted; extremely complex and difficult to follow.",
        "Debacle; a sudden and ignominious failure, a fiasco.",
        "Debilitate; to make someone weak and infirm.",
        "Debunk; to expose the falseness or hollowness of a myth, idea, or belief.",
        "Decadent; characterized by or reflecting a state of moral or cultural decline.",
        "Deference; humble submission and respect.",
        "Defunct; no longer existing or functioning.",
        "Deliberate; done consciously and intentionally.",
        "Deluge; a severe flood.",
        "Demagogue; a political leader who seeks support by appealing to the desires and prejudices of ordinary people rather than by using rational argument.",
        "Demure; reserved, modest, and shy.",
        "Denigrate; to criticize unfairly, disparage.",
        "Denounce; to publicly declare to be wrong or evil.",
        "Depict; to represent by a drawing, painting, or other art form.",
        "Deplete; to use up the supply or resources of.",
        "Deplore; to feel or express strong disapproval of something.",
        "Deride; to express contempt for, ridicule.",
        "Despondent; in low spirits from loss of hope or courage.",
        "Detriment; the state of being harmed or damaged.",
        "Devoid; entirely lacking or free from.",
        "Dexterous; demonstrating neat skill, especially with the hands.",
        "Didactic; intended to teach, particularly in having moral instruction as an ulterior motive.",
        "Diffident; modest or shy because of a lack of self-confidence.",
        "Diligent; having or showing care and conscientiousness in one's work or duties.",
        "Discern; to perceive or recognize something.",
        "Discrepancy; a lack of compatibility or similarity between two or more facts.",
        "Disdain; the feeling that someone or something is unworthy of one's consideration or respect.",
        "Disparage; to regard or represent as being of little worth.",
        "Disparate; essentially different in kind, not allowing comparison.",
        "Disseminate; to spread something, especially information, widely.",
        "Dissent; the expression or holding of opinions at variance with those previously, commonly, or officially held.",
        "Distend; to swell or cause to swell by pressure from inside.",
        "Diverge; to separate from another route, especially a main one, and go in a different direction.",
        "Divulge; to make known private or sensitive information.",
        "Docile; ready to accept control or instruction, submissive.",
        "Dogmatic; inclined to lay down principles as incontrovertibly true.",
        "Dubious; hesitating or doubting.",
        "Duress; threats, violence, constraints, or other action brought to bear on someone to do something against their will or better judgment.",
        "Dysfunction; abnormality or impairment in the function of a specified bodily organ or system.",
        "Dystopia; an imagined state or society in which there is great suffering or injustice, typically one that is totalitarian or post-apocalyptic.",
        "Ebullient; cheerful and full of energy.",
        "Eccentric; unconventional and slightly strange.",
        "Eclectic; deriving ideas, style, or taste from a broad and diverse range of sources.",
        "Efficacious; successful in producing a desired or intended result, effective.",
        "Effusive; expressing feelings of gratitude, pleasure, or approval in an unrestrained or heartfelt manner.",
        "Egregious; outstandingly bad, shocking.",
        "Eloquent; fluent or persuasive in speaking or writing.",
        "Elucidate; to make something clear, explain.",
        "Elusive; difficult to find, catch, or achieve.",
        "Embellish; to make something more attractive by the addition of decorative details or features.",
        "Eminent; famous and respected within a particular sphere or profession.",
        "Empathy; the ability to understand and share the feelings of another.",
        "Emulate; to match or surpass a person or achievement, typically by imitation.",
        "Enervate; to cause someone to feel drained of energy or vitality, weaken.",
        "Enigma; a person or thing that is mysterious, puzzling, or difficult to understand.",
        "Enmity; the state or feeling of being actively opposed or hostile to someone or something.",
        "Ephemeral; lasting for a very short time.",
        "Equanimity; mental calmness, composure, and evenness of temper, especially in a difficult situation.",
        "Equivocate; to use ambiguous language so as to conceal the truth or avoid committing oneself.",
        "Eradicate; to destroy completely, put an end to.",
        "Erudite; having or showing great knowledge or learning.",
        "Esoteric; intended for or likely to be understood by only a small number of people with a specialized knowledge or interest.",
        "Ethereal; extremely delicate and light in a way that seems too perfect for this world.",
        "Euphemism; a mild or indirect word or expression substituted for one considered to be too harsh or blunt when referring to something unpleasant or embarrassing.",
        "Euphoria; a feeling or state of intense excitement and happiness.",
        "Evanescent; soon passing out of sight, memory, or existence, quickly fading or disappearing.",
        "Exacerbate; to make a problem, bad situation, or negative feeling worse.",
        "Exculpate; to show or declare that someone is not guilty of wrongdoing.",
        "Exemplary; serving as a desirable model, representing the best of its kind.",
        "Exhort; to strongly encourage or urge someone to do something.",
        "Exigent; pressing, demanding.",
        "Exonerate; to absolve someone from blame for a fault or wrongdoing, especially after due consideration of the case.",
        "Exorbitant; unreasonably high, excessive.",
        "Expedite; to make an action or process happen sooner or be accomplished more quickly.",
        "Extol; to praise enthusiastically.",
        "Extraneous; irrelevant or unrelated to the subject being dealt with.",
        "Extrapolate; to infer or estimate by extending or projecting known information.",
        "Facetious; treating serious issues with deliberately inappropriate humor.",
        "Fallacy; a mistaken belief, especially one based on unsound argument.",
        "Fastidious; very attentive to and concerned about accuracy and detail.",
        "Fatuous; silly and pointless.",
        "Fecund; producing or capable of producing an abundance of offspring or new growth, fertile.",
        "Feeble; lacking physical strength, especially as a result of age or illness.",
        "Felicity; intense happiness, the ability to find appropriate expression for one's thoughts.",
        "Fervent; having or displaying a passionate intensity.",
        "Fiasco; a complete failure, especially a ludicrous or humiliating one.",
        "Fidelity; faithfulness to a person, cause, or belief, demonstrated by continuing loyalty and support.",
        "Flabbergasted; extremely surprised or shocked.",
        "Flamboyant; tending to attract attention because of their exuberance, confidence, and stylishness.",
        "Fleeting; lasting for a very short time.",
        "Flippant; not showing a serious or respectful attitude.",
        "Florid; having a red or flushed complexion, elaborately or excessively intricate or complicated.",
        "Fluctuate; to rise and fall irregularly in number or amount.",
        "Forbearance; patient self-control, restraint and tolerance.",
        "Foreboding; fearful apprehension, a feeling that something bad will happen.",
        "Formidable; inspiring fear or respect through being impressively large, powerful, intense, or capable.",
        "Fortuitous; happening by accident or chance rather than design.",
        "Fractious; irritable and quarrelsome.",
        "Fraught; filled with or likely to result in something undesirable.",
        "Frivolous; not having any serious purpose or value.",
        "Frugal; sparing or economical with regard to money or food.",
        "Furtive; attempting to avoid notice or attention, typically because of guilt or a belief that discovery would lead to trouble.",
        "Futile; incapable of producing any useful result, pointless.",
        "Fathom; understand after much thought.",
        "Feckless; lacking initiative or strength of character, irresponsible.",
        "Felicitous; well chosen or suited to the circumstances.",
        "Foment; instigate or stir up an undesirable or violent sentiment or course of action.",
        "Fraternize; associate or form a friendship with someone, especially when one is not supposed to.",
        "Fulsome; complimentary or flattering to an excessive degree.",
        "Fundamental; forming a necessary base or core, of central importance.",
        "Furtive; attempting to avoid notice or attention, typically because of guilt or a belief that discovery would lead to trouble.",
        "Fusillade; a series of shots fired or missiles thrown all at the same time or in quick succession.",
        "Furtive; attempting to avoid notice or attention, typically because of guilt or a belief that discovery would lead to trouble.",
        "Frisson; a sudden strong feeling of excitement or fear, a thrill.",
        "Garrulous; excessively talkative, especially on trivial matters.",
        "Gauche; lacking ease or grace, unsophisticated and socially awkward.",
        "Genial; friendly and cheerful.",
        "Germane; relevant to a subject under consideration.",
        "Gesticulate; to use gestures, especially dramatic ones, instead of speaking or to emphasize one's words.",
        "Glib; fluent and voluble but insincere and shallow.",
        "Gluttony; habitual greed or excess in eating.",
        "Goad; to provoke or annoy someone so as to stimulate some action or reaction.",
        "Gregarious; fond of company, sociable.",
        "Grievous; very severe or serious.",
        "Grotesque; comically or repulsively ugly or distorted.",
        "Guile; sly or cunning intelligence.",
        "Gullible; easily persuaded to believe something, credulous.",
        "Gumption; shrewd or spirited initiative and resourcefulness.",
        "Gaunt; lean and haggard, especially because of suffering, hunger, or age.",
        "Gainsay; to deny or contradict a fact or statement.",
        "Galvanize; to shock or excite someone into taking action.",
        "Gambit; a device, action, or opening remark, typically one entailing a degree of risk, that is calculated to gain an advantage.",
        "Gamut; the complete range or scope of something.",
        "Gargantuan; enormous.",
        "Genteel; polite, refined, or respectable, often in an affected or ostentatious way.",
        "Germinate; to begin to grow and put out shoots after a period of dormancy.",
        "Ghastly; causing great horror or fear, frightful or macabre.",
        "Giddy; having a sensation of whirling and a tendency to fall or stagger, dizzy.",
        "Girth; the measurement around the middle of something, especially a person's waist.",
        "Glacial; extremely cold or unfriendly, very slow-moving.",
        "Glean; to extract information from various sources.",
        "Glower; to have an angry or sullen look on one's face, scowl.",
        "Glut; an excessively abundant supply of something.",
        "Grandiose; impressive or magnificent in appearance or style, especially pretentiously so.",
        "Gratuitous; uncalled for, lacking good reason, unwarranted.",
        "Gregarious; sociable, enjoying the company of others.",
        "Grievous; causing sorrow or pain, serious.",
        "Grimace; an ugly, twisted expression on a person's face, typically expressing disgust, pain, or wry amusement.",
        "Grovel; to lie or crawl abjectly on the ground with one's face downward.",
        "Guileless; devoid of guile, innocent and without deception.",
        "Gullible; easily deceived or tricked.",
        "Gumption; courage and initiative, resourcefulness.",
        "Gyrate; to move or cause to move rapidly in a circle or spiral.",
        "Gyre; a spiral or vortex.",
        "Hackneyed; lacking significance through having been overused, unoriginal and trite.",
        "Hapless; unfortunate.",
        "Harangue; a lengthy and aggressive speech.",
        "Harbinger; a person or thing that announces or signals the approach of another.",
        "Haughty; arrogantly superior and disdainful.",
        "Haven; a place of safety or refuge.",
        "Hedonist; a person who believes that the pursuit of pleasure is the most important thing in life.",
        "Heinous; utterly odious or wicked.",
        "Heresy; belief or opinion contrary to orthodox religious doctrine.",
        "Hiatus; a pause or gap in a sequence, series, or process.",
        "Histrionic; overly theatrical or melodramatic in character or style.",
        "Hoax; a humorous or malicious deception.",
        "Hodgepodge; a confused mixture.",
        "Homage; special honor or respect shown publicly.",
        "Homogeneous; of the same kind, alike.",
        "Hubris; excessive pride or self-confidence.",
        "Humdrum; lacking excitement or variety, dull, monotonous.",
        "Hyperbole; exaggerated statements or claims not meant to be taken literally.",
        "Hypocrisy; the practice of claiming to have moral standards or beliefs to which one's own behavior does not conform.",
        "Hypothetical; based on or serving as a hypothesis.",
        "Hallowed; made holy, consecrated.",
        "Hamper; to hinder or impede the movement or progress of.",
        "Haphazard; lacking any obvious principle of organization.",
        "Harass; to subject to aggressive pressure or intimidation.",
        "Hardy; robust, capable of enduring difficult conditions.",
        "Hasten; to be quick to do something.",
        "Haughty; arrogantly superior and disdainful.",
        "Havoc; widespread destruction.",
        "Headstrong; self-willed and obstinate.",
        "Heed; to pay attention to, take notice of.",
        "Hew; to chop or cut something, especially wood, with an ax, pick, or other tools.",
        "Hinder; to create difficulties for someone or something, resulting in delay or obstruction.",
        "Hoary; grayish-white, old and trite.",
        "Holistic; characterized by the belief that the parts of something are interconnected and can be explained only by reference to the whole.",
        "Homogeneous; of the same kind, alike.",
        "Hone; to sharpen a blade, refine or perfect something over a period of time.",
        "Horde; a large group of people.",
        "Hostile; unfriendly, antagonistic.",
        "Hubbub; a chaotic din caused by a crowd of people.",
        "Humble; having or showing a modest or low estimate of one's own importance.",
        "Humility; a modest or low view of one's own importance, humbleness.",
        "Iconoclast; a person who attacks or criticizes cherished beliefs or institutions.",
        "Idiosyncrasy; a mode of behavior or way of thought peculiar to an individual.",
        "Illicit; forbidden by law, rules, or custom.",
        "Illusory; based on illusion, not real.",
        "Immaculate; perfectly clean, neat, or tidy.",
        "Immutable; unchanging over time or unable to be changed.",
        "Impartial; treating all rivals or disputants equally, fair and just.",
        "Impassioned; filled with or showing great emotion.",
        "Impeccable; in accordance with the highest standards of propriety, faultless.",
        "Impediment; a hindrance or obstruction in doing something.",
        "Imperative; of vital importance, crucial.",
        "Imperious; assuming power or authority without justification, arrogant and domineering.",
        "Impetuous; acting or done quickly and without thought or care.",
        "Implicit; implied though not plainly expressed.",
        "Imposing; grand and impressive in appearance.",
        "Impoverished; reduced to poverty.",
        "Impregnable; unable to be captured or broken into.",
        "Impromptu; done without being planned, organized, or rehearsed.",
        "Inadvertent; not resulting from or achieved through deliberate planning.",
        "Inane; silly, stupid.",
        "Inarticulate; unable to speak distinctly or express oneself clearly.",
        "Incendiary; designed to cause fires.",
        "Incessant; continuing without pause or interruption.",
        "Incisive; intelligently analytical and clear-thinking.",
        "Incorrigible; not able to be corrected, improved, or reformed.",
        "Incredulous; unwilling or unable to believe something.",
        "Indefatigable; persisting tirelessly.",
        "Indelible; making marks that cannot be removed.",
        "Indigenous; originating or occurring naturally in a particular place, native.",
        "Indigent; poor, needy.",
        "Indolent; wanting to avoid activity or exertion, lazy.",
        "Ineffable; too great or extreme to be expressed or described in words.",
        "Inept; having or showing no skill, clumsy.",
        "Inexorable; impossible to stop or prevent.",
        "Infallible; incapable of making mistakes or being wrong.",
        "Infamous; well known for some bad quality or deed.",
        "Infer; deduce or conclude information from evidence and reasoning rather than from explicit statements.",
        "Ingenuous; innocent and unsuspecting.",
        "Ingratiate; bring oneself into favor with someone by flattering or trying to please them.",
        "Inimical; tending to obstruct or harm.",
        "Iniquity; immoral or grossly unfair behavior.",
        "Innocuous; not harmful or offensive.",
        "Insatiable; impossible to satisfy.",
        "Inscrutable; impossible to understand or interpret.",
        "Insidious; proceeding in a gradual, subtle way, but with harmful effects.",
        "Insipid; lacking flavor, vigor, or interest.",
        "Insolent; showing a rude and arrogant lack of respect.",
        "Instigate; bring about or initiate an action or event.",
        "Insular; ignorant of or uninterested in cultures, ideas, or peoples outside one's own experience.",
        "Intangible; unable to be touched or grasped, not having physical presence.",
        "Interminable; endless or apparently endless.",
        "Intermittent; occurring at irregular intervals, not continuous or steady.",
        "Intransigent; unwilling or refusing to change one's views or to agree about something.",
        "Intrepid; fearless, adventurous.",
        "Intrinsic; belonging naturally, essential.",
        "Inundate; overwhelm someone with things or people to be dealt with.",
        "Inure; accustom someone to something, especially something unpleasant.",
        "Inveterate; having a particular habit, activity, or interest that is long-established and unlikely to change.",
        "Invidious; likely to arouse or incur resentment or anger in others.",
        "Irascible; having or showing a tendency to be easily angered.",
        "Ire; anger.",
        "Irksome; irritating, annoying.",
        "Irrefutable; impossible to deny or disprove.",
        "Irreverent; showing a lack of respect for people or things that are generally taken seriously.",
        "Itinerant; traveling from place to place.",
        "Jaded; tired, bored, or lacking enthusiasm, typically after having had too much of something.",
        "Jargon; special words or expressions that are used by a particular profession or group and are difficult for others to understand.",
        "Jaundiced; affected by bitterness, resentment, or envy.",
        "Jaunty; having or expressing a lively, cheerful, and self-confident manner.",
        "Jeopardy; danger of loss, harm, or failure.",
        "Jettison; to throw or drop something from an aircraft or ship.",
        "Jingoism; extreme patriotism, especially in the form of aggressive or warlike foreign policy.",
        "Jocose; playful or humorous.",
        "Jocular; fond of or characterized by joking, humorous or playful.",
        "Jostle; to push, elbow, or bump against someone roughly, typically in a crowd.",
        "Jovial; cheerful and friendly.",
        "Judicious; having, showing, or done with good judgment or sense.",
        "Juggernaut; a huge, powerful, and overwhelming force or institution.",
        "Juncture; a particular point in events or time.",
        "Jurisprudence; the theory or philosophy of law.",
        "Juxtapose; to place or deal with close together for contrasting effect.",
        "Jubilant; feeling or expressing great happiness and triumph.",
        "Justify; to show or prove to be right or reasonable.",
        "Jubilant; feeling or expressing great happiness and triumph.",
        "Judicious; having, showing, or done with good judgment or sense.",
        "Jubilant; feeling or expressing great happiness and triumph.",
        "Juxtaposition; the fact of two things being seen or placed close together with contrasting effect.",
        "Jubilant; feeling or expressing great happiness and triumph.",
        "Jurisprudence; the theory or philosophy of law.",
        "Justifiable; able to be shown to be right or reasonable, defensible.",
        "Juncture; a particular point in events or time.",
        "Juxtapose; to place or deal with close together for contrasting effect.",
        "Jaded; tired, bored, or lacking enthusiasm, typically after having had too much of something.",
        "Jeopardize; to put someone or something into a situation in which there is a danger of loss, harm, or failure.",
        "Jittery; nervous or unable to relax.",
        "Jingoistic; characterized by extreme patriotism, especially in the form of aggressive or warlike foreign policy.",
        "Jocund; cheerful and lighthearted.",
        "Journalism; the activity or profession of writing for newspapers, magazines, or news websites or preparing news to be broadcast.",
        "Joviality; the state of being cheerful and friendly.",
        "Judgmental; having or displaying an excessively critical point of view.",
        "Jurisprudential; relating to the theory or philosophy of law.",
        "Juvenile; for or relating to young people.",
        "Justification; the action of showing something to be right or reasonable.",
        "Juxtaposed; placed close together for contrasting effect.",
        "Kaleidoscope; a constantly changing pattern or sequence of elements.",
        "Keen; having or showing eagerness or enthusiasm.",
        "Ken; one's range of knowledge or sight.",
        "Kinetic; relating to or resulting from motion.",
        "Kinship; a sharing of characteristics or origins.",
        "Kitsch; art, objects, or design considered to be in poor taste because of excessive garishness or sentimentality, but sometimes appreciated in an ironic or knowing way.",
        "Knack; an acquired or natural skill at performing a task.",
        "Knavery; dishonest or unscrupulous behavior.",
        "Knead; to work dough or clay into a uniform mixture by pressing, folding, and stretching.",
        "Knickknack; a small, decorative object, especially in a house.",
        "Knotty; full of knots, complex and difficult to solve.",
        "Kudos; praise and honor received for an achievement.",
        "Kafkaesque; characteristic or reminiscent of the oppressive or nightmarish qualities of Franz Kafka's fictional world.",
        "Kale; a type of cabbage with curly or fringed leaves.",
        "Keystone; the central principle or part of a policy, system, etc., on which all else depends.",
        "Kindle; to light or set on fire.",
        "Kith; one's friends, acquaintances, and relations.",
        "Knavish; dishonest or unscrupulous.",
        "Kowtow; to act in an excessively subservient manner.",
        "Kilter; good condition, order.",
        "Keel; the longitudinal structure along the centerline at the bottom of a vessel's hull, on which the rest of the hull is built.",
        "Keen; highly developed, sharp.",
        "Kindred; similar in kind, related.",
        "Knot; a fastening made by tying a piece of string, rope, or something similar.",
        "Knoll; a small hill or mound.",
        "Kernel; the central or most important part of something.",
        "Kinesthetic; relating to a person's awareness of the position and movement of the parts of the body by means of sensory organs in the muscles and joints.",
        "Kindle; to arouse or inspire an emotion or feeling.",
        "Kingpin; the most important person in an organization or activity.",
        "Kleptomania; a recurrent urge to steal, typically without regard for need or profit.",
        "Kilter; out of harmony or balance.",
        "Kudos; acclaim or praise for exceptional achievement.",
        "Keenly; intensely or eagerly.",
        "Kibitz; to look on and offer unwelcome advice, especially at a card game.",
        "Kinetic; relating to or resulting from motion.",
        "Knave; a dishonest or unscrupulous man.",
        "Knightly; relating to or characteristic of a knight, especially in being chivalrous, noble, or brave.",
        "Knockabout; involving or characterized by rough, energetic, or unrestrained activity.",
        "Kook; a crazy or eccentric person.",
        "Kudos; praise and honor received for an achievement.",
        "Kymograph; an instrument for recording variations in pressure, such as in sound waves or blood flow.",
        "Labyrinth; a complicated irregular network of passages or paths in which it is difficult to find one's way, a maze.",
        "Laconic; using very few words.",
        "Lament; a passionate expression of grief or sorrow.",
        "Languid; displaying or having a disinclination for physical exertion or effort, slow and relaxed.",
        "Laudable; deserving praise and commendation.",
        "Lethargic; affected by lethargy, sluggish and apathetic.",
        "Leverage; the exertion of force by means of a lever or an object used in the manner of a lever.",
        "Levity; humor or frivolity, especially the treatment of a serious matter with humor or in a manner lacking due respect.",
        "Liaison; communication or cooperation that facilitates a close working relationship between people or organizations.",
        "Libel; a published false statement that is damaging to a person's reputation, a written defamation.",
        "Licentious; promiscuous and unprincipled in sexual matters.",
        "Lithe; thin, supple, and graceful.",
        "Livid; furiously angry.",
        "Loquacious; tending to talk a great deal, talkative.",
        "Lugubrious; looking or sounding sad and dismal.",
        "Luminary; a person who inspires or influences others, especially one prominent in a particular sphere.",
        "Lurid; very vivid in color, especially so as to create an unpleasantly harsh or unnatural effect.",
        "Lustrous; having luster, shining.",
        "Lackluster; lacking in vitality, force, or conviction, uninspired or uninspiring.",
        "Laconic; using very few words.",
        "Lambaste; criticize someone or something harshly.",
        "Languish; lose or lack vitality, grow weak or feeble.",
        "Lassitude; a state of physical or mental weariness, lack of energy.",
        "Latent; existing but not yet developed or manifest, hidden or concealed.",
        "Laud; praise a person or their achievements highly, especially in a public context.",
        "Lax; not sufficiently strict, severe, or careful.",
        "Leery; cautious or wary due to realistic suspicions.",
        "Legible; clear enough to read.",
        "Lenient; more merciful or tolerant than expected.",
        "Leverage; the exertion of force by means of a lever.",
        "Levitate; rise or cause to rise and hover in the air, typically by means of supposed magical powers.",
        "Lexicon; the vocabulary of a person, language, or branch of knowledge.",
        "Liaise; establish a working relationship, typically in order to cooperate on a matter of mutual concern.",
        "Liberal; open to new behavior or opinions and willing to discard traditional values.",
        "Libertine; a person who behaves without moral principles or a sense of responsibility, especially in sexual matters.",
        "Lilliputian; trivial or very small.",
        "Liminal; relating to a transitional or initial stage of a process.",
        "Limn; depict or describe in painting or words.",
        "Limpid; completely clear and transparent.",
        "Lithe; thin, supple, and graceful.",
        "Lodestar; a star that is used to guide the course of a ship, especially Polaris.",
        "Loquacity; the quality of being wordy and talkative.",
        "Lucid; expressed clearly, easy to understand.",
        "Luminous; full of or shedding light, bright or shining, especially in the dark.",
        "Lurid; presented in vividly shocking or sensational terms, especially giving explicit details of crimes or sexual matters.",
        "Machiavellian; cunning, scheming, and unscrupulous, especially in politics.",
        "Magnanimous; very generous or forgiving, especially toward a rival or someone less powerful than oneself.",
        "Maladroit; ineffective or bungling, clumsy.",
        "Malfeasance; wrongdoing, especially by a public official.",
        "Malleable; easily influenced, pliable.",
        "Maverick; an unorthodox or independent-minded person.",
        "Mawkish; sentimental in a feeble or sickly way.",
        "Melancholy; a feeling of pensive sadness, typically with no obvious cause.",
        "Mellifluous; sweet or musical, pleasant to hear.",
        "Menagerie; a collection of wild animals kept in captivity for exhibition.",
        "Mendacious; not telling the truth, lying.",
        "Mercurial; subject to sudden or unpredictable changes of mood or mind.",
        "Meretricious; apparently attractive but having in reality no value or integrity.",
        "Meticulous; showing great attention to detail, very careful and precise.",
        "Miasma; a highly unpleasant or unhealthy smell or vapor.",
        "Milieu; a person's social environment.",
        "Mirth; amusement, especially as expressed in laughter.",
        "Misnomer; a wrong or inaccurate name or designation.",
        "Mitigate; make less severe, serious, or painful.",
        "Modicum; a small quantity of a particular thing, especially something considered desirable or valuable.",
        "Mollify; appease the anger or anxiety of someone.",
        "Monotonous; dull, tedious, and repetitious, lacking in variety and interest.",
        "Morose; sullen and ill-tempered.",
        "Munificent; more generous than is usual or necessary.",
        "Myopic; nearsighted, lacking imagination, foresight, or intellectual insight.",
        "Mystique; a fascinating aura of mystery, awe, and power surrounding someone or something.",
        "Macabre; disturbing and horrifying because of involvement with or depiction of death and injury.",
        "Malady; a disease or ailment.",
        "Malcontent; a person who is dissatisfied and rebellious.",
        "Malevolent; having or showing a wish to do evil to others.",
        "Malignant; very virulent or infectious, malevolent.",
        "Mandate; an official order or commission to do something.",
        "Manifest; clear or obvious to the eye or mind.",
        "Mansuetude; meekness, gentleness.",
        "Maudlin; self-pityingly or tearfully sentimental, often through drunkenness.",
        "Maven; an expert or connoisseur.",
        "Meddlesome; fond of meddling, interfering.",
        "Mellifluous; sweet or musical, pleasant to hear.",
        "Menacing; suggesting the presence of danger, threatening.",
        "Mercenary; primarily concerned with making money at the expense of ethics.",
        "Meritorious; deserving reward or praise.",
        "Metamorphosis; a change of the form or nature of a thing or person into a completely different one, by natural or supernatural means.",
        "Metaphor; a figure of speech in which a word or phrase is applied to an object or action to which it is not literally applicable.",
        "Meticulous; showing great attention to detail, very careful and precise.",
        "Mimicry; the action or art of imitating someone or something, typically to entertain or ridicule.",
        "Misanthrope; a person who dislikes humankind and avoids human society.",
        "Misdemeanor; a minor wrongdoing.",
        "Mitigating; making less severe, serious, or painful.",
        "Mnemonic; aiding or designed to aid the memory.",
        "Mollify; to appease the anger or anxiety of someone.",
        "Monolithic; large, powerful, and intractably indivisible and uniform.",
        "Moratorium; a temporary prohibition of an activity.",
        "Mordant; having or showing a sharp or critical quality, biting.",
        "Munificent; more generous than is usual or necessary.",
        "Myriad; a countless or extremely great number.",
        "Nadir; the lowest point in the fortunes of a person or organization.",
        "Narcissistic; having an excessive interest in or admiration of oneself and one's physical appearance.",
        "Nascent; just coming into existence and beginning to display signs of future potential.",
        "Nefarious; wicked or criminal.",
        "Negligible; so small or unimportant as to be not worth considering, insignificant.",
        "Nemesis; a long-standing rival, an archenemy.",
        "Neophyte; a person who is new to a subject, skill, or belief.",
        "Nettle; to irritate or annoy someone.",
        "Nexus; a connection or series of connections linking two or more things.",
        "Nihilism; the rejection of all religious and moral principles, often in the belief that life is meaningless.",
        "Nimble; quick and light in movement or action, agile.",
        "Nomadic; living the life of a nomad, wandering.",
        "Nomenclature; the devising or choosing of names for things, especially in a science or other discipline.",
        "Nonchalant; feeling or appearing casually calm and relaxed, not displaying anxiety, interest, or enthusiasm.",
        "Nondescript; lacking distinctive or interesting features or characteristics.",
        "Nostalgia; a sentimental longing or wistful affection for the past, typically for a period or place with happy personal associations.",
        "Notoriety; the state of being famous or well known for some bad quality or deed.",
        "Novel; new or unusual in an interesting way.",
        "Noxious; harmful, poisonous, or very unpleasant.",
        "Nuance; a subtle difference in or shade of meaning, expression, or sound.",
        "Nugatory; of no value or importance.",
        "Nurture; to care for and encourage the growth or development of.",
        "Nadir; the lowest point in the fortunes of a person or organization.",
        "Nefarious; wicked or criminal.",
        "Negate; to nullify, make ineffective.",
        "Negligent; failing to take proper care in doing something.",
        "Neologism; a newly coined word or expression.",
        "Nettle; to irritate or annoy someone.",
        "Nimble; quick and light in movement or action, agile.",
        "Nominal; existing in name only, not real or actual.",
        "Nonplus; to surprise and confuse someone so much that they are unsure how to react.",
        "Nostalgic; characterized by or exhibiting feelings of nostalgia.",
        "Noteworthy; deserving attention, remarkable.",
        "Nubile; (of a young woman) sexually mature, suitable for marriage.",
        "Nugatory; of no value or importance.",
        "Nurturing; promoting the growth or development of someone or something.",
        "Nuzzle; to rub or push against gently with the nose and mouth.",
        "Obdurate; stubbornly refusing to change one's opinion or course of action.",
        "Obfuscate; to render obscure, unclear, or unintelligible.",
        "Oblivious; not aware of or not concerned about what is happening around one.",
        "Obnoxious; extremely unpleasant.",
        "Obsequious; obedient or attentive to an excessive or servile degree.",
        "Obsolete; no longer produced or used, out of date.",
        "Obstinate; stubbornly refusing to change one's opinion or chosen course of action, despite attempts to persuade one to do so.",
        "Obstreperous; noisy and difficult to control.",
        "Obtuse; annoyingly insensitive or slow to understand.",
        "Obviate; to remove a need or difficulty.",
        "Occlude; to stop, close up, or obstruct an opening, orifice, or passage.",
        "Occult; mystical, supernatural, or magical powers, practices, or phenomena.",
        "Odious; extremely unpleasant, repulsive.",
        "Odyssey; a long and eventful or adventurous journey or experience.",
        "Ogle; to stare at in a lecherous manner.",
        "Olfactory; relating to the sense of smell.",
        "Ominous; giving the impression that something bad or unpleasant is going to happen, threatening.",
        "Omnipotent; having unlimited power, able to do anything.",
        "Omniscient; knowing everything.",
        "Onus; used to refer to something that is one's duty or responsibility.",
        "Opaque; not able to be seen through, not transparent.",
        "Opulent; ostentatiously rich and luxurious or lavish.",
        "Orator; a public speaker, especially one who is eloquent or skilled.",
        "Ornate; made in an intricate shape or decorated with complex patterns.",
        "Ostensible; stated or appearing to be true, but not necessarily so.",
        "Ostentatious; characterized by vulgar or pretentious display, designed to impress or attract notice.",
        "Ostracize; to exclude someone from a society or group.",
        "Oust; to drive out or expel someone from a position or place.",
        "Outlandish; looking or sounding bizarre or unfamiliar.",
        "Outmoded; old-fashioned.",
        "Overt; done or shown openly, plainly or readily apparent, not secret or hidden.",
        "Oxymoron; a figure of speech in which apparently contradictory terms appear in conjunction.",
        "Onerous; involving a great deal of effort, trouble, or difficulty.",
        "Opine; to hold and state as one's opinion.",
        "Ornery; bad-tempered and combative.",
        "Orthodox; conforming to what is generally or traditionally accepted as right or true, established and approved.",
        "Oscillate; to move or swing back and forth at a regular speed.",
        "Ovation; a sustained and enthusiastic show of appreciation from an audience, especially by means of applause.",
        "Overwhelm; to bury or drown beneath a huge mass.",
        "Overzealous; too zealous in attitude or behavior.",
        "Oxidize; to combine or become combined chemically with oxygen.",
        "Pacify; to quell the anger, agitation, or excitement of.",
        "Palliate; to make a disease or its symptoms less severe or unpleasant without removing the cause.",
        "Palpable; able to be touched or felt.",
        "Paltry; small or meager, petty or trivial.",
        "Panacea; a solution or remedy for all difficulties or diseases.",
        "Pandemic; an outbreak of a disease prevalent over a whole country or the world.",
        "Paradigm; a typical example or pattern of something, a model.",
        "Paragon; a person or thing regarded as a perfect example of a particular quality.",
        "Pariah; an outcast.",
        "Parochial; relating to a church parish, having a limited or narrow outlook or scope.",
        "Parody; an imitation of the style of a particular writer, artist, or genre with deliberate exaggeration for comic effect.",
        "Parsimonious; unwilling to spend money or use resources, stingy or frugal.",
        "Pathos; a quality that evokes pity or sadness.",
        "Patronize; to treat with an apparent kindness that betrays a feeling of superiority.",
        "Paucity; the presence of something only in small or insufficient quantities or amounts, scarcity.",
        "Pejorative; expressing contempt or disapproval.",
        "Pellucid; translucently clear.",
        "Penchant; a strong or habitual liking for something or tendency to do something.",
        "Penitent; feeling or showing sorrow and regret for having done wrong, repentant.",
        "Pensive; engaged in, involving, or reflecting deep or serious thought.",
        "Perfunctory; carried out with a minimum of effort or reflection.",
        "Peripatetic; traveling from place to place, especially working or based in various places for relatively short periods.",
        "Permeate; to spread throughout something, pervade.",
        "Pernicious; having a harmful effect, especially in a gradual or subtle way.",
        "Perspicacious; having a ready insight into and understanding of things.",
        "Pertinent; relevant or applicable to a particular matter, apposite.",
        "Pervasive; spreading widely throughout an area or a group of people.",
        "Petulant; childishly sulky or bad-tempered.",
        "Philanthropy; the desire to promote the welfare of others, expressed especially by the generous donation of money to good causes.",
        "Phlegmatic; having an unemotional and stolidly calm disposition.",
        "Piety; the quality of being religious or reverent.",
        "Pinnacle; the most successful point, the culmination.",
        "Pithy; concise and forcefully expressive.",
        "Placate; to make someone less angry or hostile.",
        "Platitude; a remark or statement, especially one with a moral content, that has been used too often to be interesting or thoughtful.",
        "Plausible; seeming reasonable or probable.",
        "Plebian; a commoner, a member of the lower social classes.",
        "Plethora; a large or excessive amount of something.",
        "Poignant; evoking a keen sense of sadness or regret.",
        "Polemical; relating to or involving strongly critical, controversial, or disputatious writing or speech.",
        "Polygot; knowing or using several languages.",
        "Ponderous; slow and clumsy because of great weight.",
        "Portend; to be a sign or warning that something, especially something momentous or calamitous, is likely to happen.",
        "Pragmatic; dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.",
        "Precarious; not securely held or in position, dangerously likely to fall or collapse.",
        "Preclude; to prevent from happening, make impossible.",
        "Precocious; having developed certain abilities or proclivities at an earlier age than usual.",
        "Predilection; a preference or special liking for something, a bias in favor of something.",
        "Preeminent; surpassing all others, very distinguished in some way.",
        "Premonition; a strong feeling that something is about to happen, especially something unpleasant.",
        "Prescient; having or showing knowledge of events before they take place.",
        "Prevaricate; to speak or act in an evasive way.",
        "Pristine; in its original condition, unspoiled.",
        "Probity; the quality of having strong moral principles, honesty and decency.",
        "Proclivity; a tendency to choose or do something regularly, an inclination or predisposition toward a particular thing.",
        "Procrastinate; to delay or postpone action, put off doing something.",
        "Profligate; recklessly extravagant or wasteful in the use of resources.",
        "Prolific; producing much fruit or foliage or many offspring.",
        "Propensity; an inclination or natural tendency to behave in a particular way.",
        "Propitious; giving or indicating a good chance of success, favorable.",
        "Prosaic; having the style or diction of prose, lacking poetic beauty.",
        "Protean; tending or able to change frequently or easily.",
        "Provocative; causing annoyance, anger, or another strong reaction, especially deliberately.",
        "Prudent; acting with or showing care and thought for the future.",
        "Puerile; childishly silly and trivial.",
        "Pugnacious; eager or quick to argue, quarrel, or fight.",
        "Pulchritude; beauty.",
        "Quaint; attractively unusual or old-fashioned.",
        "Quagmire; a soft boggy area of land that gives way underfoot, a complex or hazardous situation.",
        "Quail; to feel or show fear or apprehension.",
        "Qualitative; relating to, measuring, or measured by the quality of something rather than its quantity.",
        "Quandary; a state of perplexity or uncertainty over what to do in a difficult situation.",
        "Quarantine; a state, period, or place of isolation in which people or animals that have arrived from elsewhere or been exposed to infectious or contagious disease are placed.",
        "Quarrelsome; given to or characterized by quarreling.",
        "Quash; to reject or void, especially by legal procedure.",
        "Querulous; complaining in a petulant or whining manner.",
        "Quiescent; in a state or period of inactivity or dormancy.",
        "Quintessential; representing the most perfect or typical example of a quality or class.",
        "Quixotic; exceedingly idealistic, unrealistic and impractical.",
        "Quizzical; indicating mild or amused puzzlement.",
        "Quotidian; of or occurring every day, daily.",
        "Quasi; seemingly, apparently but not really, being partly or almost.",
        "Quaff; to drink heartily.",
        "Quarantine; a period of isolation to prevent the spread of disease.",
        "Quarry; a place, typically a large, deep pit, from which stone or other materials are or have been extracted.",
        "Quell; to put an end to a rebellion or other disorder, typically by the use of force.",
        "Querulous; complaining in a petulant or whining manner.",
        "Quiescent; in a state or period of inactivity or dormancy.",
        "Quintessence; the most perfect or typical example of a quality or class.",
        "Quizzical; indicating mild or amused puzzlement.",
        "Quirk; a peculiar aspect of a person's character or behavior.",
        "Quota; a fixed share of something that a person or group is entitled to receive or is bound to contribute.",
        "Quotidian; of or occurring every day, daily.",
        "Quixotic; exceedingly idealistic, unrealistic and impractical.",
        "Quorum; the minimum number of members of an assembly or society that must be present at any of its meetings to make the proceedings of that meeting valid.",
        "Quash; to reject or void, especially by legal procedure.",
        "Quarantine; a state, period, or place of isolation.",
        "Quibble; a slight objection or criticism.",
        "Quintessential; representing the most perfect or typical example of a quality or class.",
        "Quip; a witty remark.",
        "Quiescent; in a state or period of inactivity or dormancy.",
        "Quintuple; consisting of five parts or things.",
        "Quirk; a peculiar aspect of a person's character or behavior.",
        "Quintessence; the most perfect or typical example of a quality or class.",
        "Quiver; to tremble or shake with a slight rapid motion.",
        "Quixotic; exceedingly idealistic, unrealistic and impractical.",
        "Quizzical; indicating mild or amused puzzlement.",
        "Quotidian; of or occurring every day, daily.",
        "Raconteur; a person who tells anecdotes in a skillful and amusing way.",
        "Radical; relating to or affecting the fundamental nature of something, far-reaching or thorough.",
        "Ramification; a consequence of an action or event, especially when complex or unwelcome.",
        "Rancor; bitterness or resentfulness, especially when long-standing.",
        "Rapport; a close and harmonious relationship in which the people or groups concerned understand each other's feelings or ideas and communicate well.",
        "Rapt; completely fascinated by what one is seeing or hearing.",
        "Raspy; hoarse or harsh-sounding.",
        "Raucous; making or constituting a disturbingly harsh and loud noise.",
        "Ravenous; extremely hungry.",
        "Raze; to completely destroy a building, town, or other site.",
        "Rebuff; to reject someone or something in an abrupt or ungracious manner.",
        "Recant; to say that one no longer holds an opinion or belief, especially one considered heretical.",
        "Recapitulate; to summarize and state again the main points of.",
        "Recluse; a person who lives a solitary life and tends to avoid other people.",
        "Recondite; little known, abstruse.",
        "Rectify; to put something right, correct.",
        "Redolent; strongly reminiscent or suggestive of something.",
        "Redress; remedy or set right an undesirable or unfair situation.",
        "Refractory; stubborn or unmanageable.",
        "Refute; to prove a statement or theory to be wrong or false, disprove.",
        "Regale; to entertain or amuse someone with talk.",
        "Relegate; to consign or dismiss to an inferior rank or position.",
        "Relinquish; to voluntarily cease to keep or claim, give up.",
        "Remiss; lacking care or attention to duty, negligent.",
        "Remonstrate; to make a forcefully reproachful protest.",
        "Renounce; to formally declare one's abandonment of a claim, right, or possession.",
        "Replete; filled or well-supplied with something.",
        "Reprehensible; deserving censure or condemnation.",
        "Repress; to subdue someone or something by force.",
        "Reproach; to address someone in such a way as to express disapproval or disappointment.",
        "Reprobate; an unprincipled person.",
        "Repudiate; to refuse to accept or be associated with.",
        "Rescind; to revoke, cancel, or repeal a law, order, or agreement.",
        "Resilient; able to withstand or recover quickly from difficult conditions.",
        "Resolute; admirably purposeful, determined, and unwavering.",
        "Resonant; deep, clear, and continuing to sound or ring.",
        "Reticent; not revealing one's thoughts or feelings readily.",
        "Retort; to say something in answer to a remark or accusation, typically in a sharp, angry, or wittily incisive manner.",
        "Revere; to feel deep respect or admiration for something.",
        "Rhetoric; the art of effective or persuasive speaking or writing.",
        "Rife; of common occurrence, widespread.",
        "Ruminate; to think deeply about something.",
        "Rustic; relating to the countryside, rural.",
        "Ruthless; having or showing no pity or compassion for others.",
        "Ramshackle; in a state of severe disrepair.",
        "Rapacious; aggressively greedy or grasping.",
        "Raucous; making or constituting a disturbingly harsh and loud noise.",
        "Recalcitrant; having an obstinately uncooperative attitude toward authority or discipline.",
        "Reciprocal; given, felt, or done in return.",
        "Reconnoiter; to make a military observation of a region.",
        "Rectitude; morally correct behavior or thinking, righteousness.",
        "Refulgent; shining brightly.",
        "Renegade; a person who deserts and betrays an organization, country, or set of principles.",
        "Replete; filled or well-supplied with something.",
        "Rescind; to revoke, cancel, or repeal a law, order, or agreement.",
        "Sagacious; having or showing keen mental discernment and good judgment, shrewd.",
        "Salient; most noticeable or important.",
        "Sanctimonious; making a show of being morally superior to other people.",
        "Sanguine; optimistic or positive, especially in an apparently bad or difficult situation.",
        "Sardonic; grimly mocking or cynical.",
        "Satiate; to satisfy a desire or appetite to the full.",
        "Scintillating; sparkling or shining brightly.",
        "Scrupulous; diligent, thorough, and extremely attentive to details.",
        "Scrutinize; to examine or inspect closely and thoroughly.",
        "Scurrilous; making or spreading scandalous claims about someone with the intention of damaging their reputation.",
        "Secular; denoting attitudes, activities, or other things that have no religious or spiritual basis.",
        "Sedentary; tending to spend much time seated, somewhat inactive.",
        "Semblance; the outward appearance or apparent form of something, especially when the reality is different.",
        "Serrated; having or denoting a jagged edge, sawlike.",
        "Servile; having or showing an excessive willingness to serve or please others.",
        "Skeptical; not easily convinced, having doubts or reservations.",
        "Skulduggery; underhanded or unscrupulous behavior, trickery.",
        "Slander; the action or crime of making a false spoken statement damaging to a person's reputation.",
        "Slipshod; characterized by a lack of care, thought, or organization.",
        "Solace; comfort or consolation in a time of distress or sadness.",
        "Solicitous; characterized by or showing interest or concern.",
        "Soporific; tending to induce drowsiness or sleep.",
        "Spartan; showing the indifference to comfort or luxury traditionally associated with ancient Sparta.",
        "Specious; superficially plausible, but actually wrong.",
        "Splenetic; bad-tempered, spiteful.",
        "Spurious; not being what it purports to be, false or fake.",
        "Stalwart; loyal, reliable, and hardworking.",
        "Staunch; loyal and committed in attitude.",
        "Stentorian; loud and powerful.",
        "Stigmatize; to describe or regard as worthy of disgrace or great disapproval.",
        "Stipulate; to demand or specify a requirement, typically as part of a bargain or agreement.",
        "Stoic; enduring pain and hardship without showing one's feelings or complaining.",
        "Stratagem; a plan or scheme, especially one used to outwit an opponent or achieve an end.",
        "Strident; loud and harsh, grating.",
        "Stultify; to cause to lose enthusiasm and initiative, especially as a result of a tedious or restrictive routine.",
        "Stupor; a state of near-unconsciousness or insensibility.",
        "Subjugate; to bring under domination or control, especially by conquest.",
        "Sublime; of such excellence, grandeur, or beauty as to inspire great admiration or awe.",
        "Substantiate; to provide evidence to support or prove the truth of.",
        "Subterfuge; deceit used in order to achieve one's goal.",
        "Succinct; briefly and clearly expressed.",
        "Succumb; to fail to resist pressure, temptation, or some other negative force.",
        "Sultry; hot and humid, or displaying a passionate nature.",
        "Supercilious; behaving or looking as though one thinks one is superior to others.",
        "Surfeit; an excessive amount of something.",
        "Surreptitious; kept secret, especially because it would not be approved of.",
        "Surrogate; a substitute, especially a person deputizing for another in a specific role or office.",
        "Sycophant; a person who acts obsequiously toward someone important in order to gain advantage.",
        "Synonymous; having the same or nearly the same meaning as another word or phrase.",
        "Systemic; relating to a system, especially as opposed to a particular part.",
        "Synthesis; the combination of ideas to form a theory or system.",
        "Sardonic; grimly mocking or cynical.",
        "Scrutinize; to examine or inspect closely and thoroughly.",
        "Tacit; understood or implied without being stated.",
        "Taciturn; reserved or uncommunicative in speech, saying little.",
        "Tactile; connected with the sense of touch.",
        "Talisman; an object, typically an inscribed ring or stone, that is thought to have magic powers and to bring good luck.",
        "Tangible; perceptible by touch, clear and definite, real.",
        "Tantamount; equivalent in seriousness to, virtually the same as.",
        "Tautological; involving or containing rhetorical tautology, redundant.",
        "Tedious; too long, slow, or dull, tiresome or monotonous.",
        "Temerity; excessive confidence or boldness, audacity.",
        "Tenacious; tending to keep a firm hold of something, clinging or adhering closely.",
        "Tendentious; expressing or intending to promote a particular cause or point of view, especially a controversial one.",
        "Tentative; not certain or fixed, provisional.",
        "Tenure; the holding of an office or the period during which one is held.",
        "Tepid; only slightly warm, lukewarm, showing little enthusiasm.",
        "Terrestrial; of, on, or relating to the earth.",
        "Terse; sparing in the use of words, abrupt.",
        "Tether; to tie an animal with a rope or chain so as to restrict its movement.",
        "Timorous; showing or suffering from nervousness, fear, or a lack of confidence.",
        "Tirade; a long, angry speech of criticism or accusation.",
        "Torpid; mentally or physically inactive, lethargic.",
        "Torrid; very hot and dry, full of difficulty or tribulation.",
        "Tortuous; full of twists and turns, excessively lengthy and complex.",
        "Tractable; easy to control or influence.",
        "Transcendent; beyond or above the range of normal or merely physical human experience.",
        "Transitory; not permanent.",
        "Travesty; a false, absurd, or distorted representation of something.",
        "Trepidation; a feeling of fear or agitation about something that may happen.",
        "Trite; overused and consequently of little import, lacking originality or freshness.",
        "Truculent; eager or quick to argue or fight, aggressively defiant.",
        "Tumultuous; making a loud, confused noise, uproarious, excited, confused, or disorderly.",
        "Turpitude; depravity, wickedness.",
        "Tutelage; protection of or authority over someone or something, guardianship.",
        "Twain; archaic term for two.",
        "Tawdry; showy but cheap and of poor quality.",
        "Temerity; excessive confidence or boldness, audacity.",
        "Tempestuous; characterized by strong and turbulent or conflicting emotion.",
        "Tenet; a principle or belief, especially one of the main principles of a religion or philosophy.",
        "Thwart; to prevent someone from accomplishing something.",
        "Timorous; showing or suffering from nervousness, fear, or a lack of confidence.",
        "Tome; a book, especially a large, heavy, scholarly one.",
        "Torrential; falling rapidly and in copious quantities, resembling a torrent in force and abundance.",
        "Tranquil; free from disturbance, calm.",
        "Transgress; to infringe or go beyond the bounds of a moral principle or other established standard of behavior.",
        "Translucent; allowing light, but not detailed images, to pass through, semitransparent.",
        "Trepidation; a feeling of fear or agitation about something that may happen.",
        "Triage; the assignment of degrees of urgency to wounds or illnesses to decide the order of treatment of a large number of patients or casualties.",
        "Tribulation; a cause of great trouble or suffering.",
        "Troglodyte; a person who lived in a cave, a hermit.",
        "Truncate; to shorten something by cutting off the top or the end.",
        "Ubiquitous; present, appearing, or found everywhere.",
        "Ulterior; existing beyond what is obvious or admitted, intentionally hidden.",
        "Ultimate; being or happening at the end of a process, final.",
        "Umbrage; offense or annoyance.",
        "Unabashed; not embarrassed, disconcerted, or ashamed.",
        "Unassuming; not pretentious or arrogant, modest.",
        "Uncanny; strange or mysterious, especially in an unsettling way.",
        "Unconscionable; not right or reasonable, unreasonably excessive.",
        "Undermine; to erode the base or foundation of something, to weaken gradually or insidiously.",
        "Unequivocal; leaving no doubt, unambiguous.",
        "Unfathomable; incapable of being fully explored or understood.",
        "Ungainly; awkward, clumsy.",
        "Unilateral; performed by or affecting only one person, group, or country involved in a particular situation, without the agreement of another or the others.",
        "Unimpeachable; not able to be doubted, questioned, or criticized, entirely trustworthy.",
        "Unique; being the only one of its kind, unlike anything else.",
        "Unkempt; having an untidy or disheveled appearance.",
        "Unobtrusive; not conspicuous or attracting attention.",
        "Unprecedented; never done or known before.",
        "Unruly; disorderly and disruptive and not amenable to discipline or control.",
        "Unscrupulous; having or showing no moral principles, not honest or fair.",
        "Unseemly; not proper or appropriate.",
        "Untoward; unexpected and inappropriate or inconvenient.",
        "Unwieldy; difficult to carry or move because of its size, shape, or weight.",
        "Urbane; courteous and refined in manner.",
        "Usurp; to take a position of power or importance illegally or by force.",
        "Utilitarian; designed to be useful or practical rather than attractive.",
        "Utopian; modeled on or aiming for a state in which everything is perfect, idealistic.",
        "Ubiquitous; present, appearing, or found everywhere.",
        "Ulterior; existing beyond what is obvious or admitted, intentionally hidden.",
        "Unanimous; fully in agreement.",
        "Unassailable; unable to be attacked, questioned, or defeated.",
        "Uncouth; lacking good manners, refinement, or grace.",
        "Undulate; to move with a smooth wavelike motion.",
        "Unearth; to find something in the ground by digging.",
        "Unequivocal; leaving no doubt, unambiguous.",
        "Unfettered; released from restraint or inhibition.",
        "Unflappable; having or showing calmness in a crisis.",
        "Ungainly; awkward, clumsy.",
        "Unison; simultaneous performance or utterance of action or speech.",
        "Unorthodox; contrary to what is usual, traditional, or accepted.",
        "Unravel; to undo twisted, knitted, or woven threads.",
        "Unrelenting; not yielding in strength, severity, or determination.",
        "Unruly; disorderly and disruptive and not amenable to discipline or control.",
        "Untethered; released or free from a tether.",
        "Unwavering; steady or resolute, not wavering.",
        "Vacillate; to waver between different opinions or actions, be indecisive.",
        "Vacuous; having or showing a lack of thought or intelligence, mindless.",
        "Vagary; an unexpected and inexplicable change in a situation or in someone's behavior.",
        "Vanguard; a group of people leading the way in new developments or ideas.",
        "Vehement; showing strong feeling, forceful, passionate, or intense.",
        "Venal; showing or motivated by susceptibility to bribery.",
        "Venerate; to regard with great respect, revere.",
        "Veracity; conformity to facts, accuracy.",
        "Verbose; using or expressed in more words than are needed.",
        "Vertigo; a sensation of whirling and loss of balance, associated particularly with looking down from a great height.",
        "Vestige; a trace of something that is disappearing or no longer exists.",
        "Vex; to make someone feel annoyed, frustrated, or worried, especially with trivial matters.",
        "Viable; capable of working successfully, feasible.",
        "Vicarious; experienced in the imagination through the feelings or actions of another person.",
        "Vicissitude; a change of circumstances or fortune, typically one that is unwelcome or unpleasant.",
        "Vigilant; keeping careful watch for possible danger or difficulties.",
        "Vilify; to speak or write about in an abusively disparaging manner.",
        "Vindicate; to clear someone of blame or suspicion.",
        "Vindictive; having or showing a strong or unreasoning desire for revenge.",
        "Virtuoso; a person highly skilled in music or another artistic pursuit.",
        "Virulent; extremely severe or harmful in its effects.",
        "Visceral; relating to deep inward feelings rather than to the intellect.",
        "Vitiate; to spoil or impair the quality or efficiency of.",
        "Vociferous; crying out noisily, clamorous.",
        "Volatile; liable to change rapidly and unpredictably, especially for the worse.",
        "Volition; the faculty or power of using one's will.",
        "Voracious; wanting or devouring great quantities of food, having a very eager approach to an activity.",
        "Vortex; a mass of whirling fluid or air, especially a whirlpool or whirlwind.",
        "Vulnerable; susceptible to physical or emotional attack or harm.",
        "Vapid; offering nothing that is stimulating or challenging, bland.",
        "Variegated; exhibiting different colors, especially as irregular patches or streaks.",
        "Vehement; showing strong feeling, forceful, passionate, or intense.",
        "Venal; showing or motivated by susceptibility to bribery.",
        "Venerate; to regard with great respect, revere.",
        "Verdant; green with grass or other rich vegetation.",
        "Veritable; used as an intensifier, often to qualify a metaphor.",
        "Vernacular; the language or dialect spoken by the ordinary people in a particular country or region.",
        "Vestigial; forming a very small remnant of something that was once much larger or more noticeable.",
        "Vicarious; experienced in the imagination through the feelings or actions of another person.",
        "Vigilante; a member of a self-appointed group of citizens who undertake law enforcement in their community without legal authority.",
        "Vilify; to speak or write about in an abusively disparaging manner.",
        "Vim; energy, enthusiasm.",
        "Visage; a person's face, with reference to the form or proportions of the features.",
        "Vista; a pleasing view, especially one seen through a long, narrow opening.",
        "Vociferous; crying out noisily, clamorous.",
        "Volatile; liable to change rapidly and unpredictably, especially for the worse.",
        "Volition; the faculty or power of using one's will.",
        "Voracious; wanting or devouring great quantities of food, having a very eager approach to an activity.",
        "Wumbo; I wumbo, you wumbo. He, she, me wumbo. Wumbology the study of wumbo. It's first grade Spongebob.",
        "Waffle; to speak or write evasively.",
        "Waft; to pass or cause to pass easily or gently through or as if through the air.",
        "Wane; to decrease in size, extent, or degree.",
        "Wangle; to obtain something that is desired by persuading others to comply or by manipulating events.",
        "Wanton; deliberate and unprovoked, sexually immodest or promiscuous.",
        "Wary; feeling or showing caution about possible dangers or problems.",
        "Waver; to shake with a quivering motion, to become unsteady or unreliable.",
        "Wayward; difficult to control or predict because of unusual or perverse behavior.",
        "Wheedle; to use flattery or coaxing in order to persuade someone to do something or give one something.",
        "Whimsical; playfully quaint or fanciful, especially in an appealing and amusing way.",
        "Whittle; to carve wood into an object by repeatedly cutting small slices from it.",
        "Wily; skilled at gaining an advantage, especially deceitfully.",
        "Winnow; to blow a current of air through grain in order to remove the chaff.",
        "Winsome; attractive or appealing in appearance or character.",
        "Wistful; having or showing a feeling of vague or regretful longing.",
        "Wizened; shriveled or wrinkled with age.",
        "Woe; great sorrow or distress.",
        "Wonderment; a state of awed admiration or respect.",
        "Wont; in the habit of doing something, accustomed.",
        "Wrangle; to have a long and complicated dispute.",
        "Wrath; extreme anger.",
        "Wreak; to cause a large amount of damage or harm.",
        "Wrest; to forcibly pull something from a person's grasp.",
        "Wretched; in a very unhappy or unfortunate state.",
        "Wry; using or expressing dry, especially mocking, humor.",
        "Wanderlust; a strong desire to travel.",
        "Wanton; deliberate and unprovoked.",
        "Waylay; to stop or interrupt someone and detain them in conversation or trouble them in some other way.",
        "Wean; to accustom someone to manage without something they have become dependent on.",
        "Welter; to move in a turbulent fashion.",
        "Whet; to sharpen the blade of a tool or weapon.",
        "Wile; devious or cunning stratagems employed in manipulating or persuading someone to do what one wants.",
        "Winsome; attractive or appealing in a fresh, innocent way.",
        "Wont; in the habit of doing something, accustomed.",
        "Wrest; to forcibly pull something from a person's grasp.",
        "Wretched; in a very unhappy or unfortunate state.",
        "Wry; using or expressing dry, especially mocking, humor.",
        "Wanderlust; a strong desire to travel.",
        "Wanton; deliberate and unprovoked.",
        "Wraith; a ghost or ghostlike image of someone, especially one seen shortly before or after their death.",
        "Wrangle; to have a long and complicated dispute.",
        "Wreak; to cause a large amount of damage or harm.",
        "Wizened; shriveled or wrinkled with age.",
        "Wistful; having or showing a feeling of vague or regretful longing.",
        "Winsome; attractive or appealing in appearance or character.",
        "Winnow; to blow a current of air through grain in order to remove the chaff.",
        "Wheedle; to use flattery or coaxing in order to persuade someone to do something or give one something.",
        "Whimsical; playfully quaint or fanciful, especially in an appealing and amusing way.",
        "Xenophobia; dislike of or prejudice against people from other countries.",
        "Xeric; containing little moisture, very dry.",
        "Xerothermic; characterized by heat and dryness.",
        "Xenial; friendly, especially to visitors and guests.",
        "Xylography; the art of engraving on wood or of printing from woodblocks.",
        "Xenodochium; a place of reception for strangers, a guesthouse.",
        "Zealot; a person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals.",
        "Zealous; having or showing great energy or enthusiasm in pursuit of a cause or objective.",
    ];
    // currently tested -- add flamingoes changing color-- flying snakes --
    const animalFacts: string[] = [
        "A cockroach can live several weeks with its head cut off.",
        "It takes a sloth two weeks to digest its food.",
        "Nearly three percent of the ice in Antarctic glaciers is penguin urine.",
        "A cow gives nearly 200,000 glasses of milk in her lifetime.",
        "During World War II, Americans tried to train bats to drop bombs.",
        "The horn of a rhinoceros is made from compacted hair rather than bone or another substance.",
        "Polar bears are nearly undetectable by infrared cameras, due to their transparent fur.",
        "Giraffes have black tongues to prevent sunburn while eating in the hot sun.",
        "In terms of weight, the largest organ in birds is their feathers.",
        "Seahorses mate for life, and when they travel, they hold each other's tails.",
        "The slowest fish is the seahorse, which moves along at about 0.01 mph.",
        "Most reptiles lay eggs, but some snakes give birth to live young.",
        "Elephants can hear one another's trumpeting calls up to 5 miles away.",
        "A rhinoceros beetle can lift objects 850 times its own weight.",
        "The sailfish is considered the fastest fish in the ocean, capable of swimming up to 68 miles per hour.",
        "Giraffes only need 5 to 30 minutes of sleep in a 24-hour period.",
        "The age of a lobster can be determined by counting its rings, similar to a tree.",
        "Some species of frogs have the incredible ability to freeze without dying, surviving harsh winter conditions.",
        "Cows have been observed to form close friendships and can become stressed if they are separated from their best friends.",
        "Dolphins are known to assign names to each other and can specifically call out to one another using those names.",
        "The Basenji dog is uniquely known as the 'barkless dog' due to its unusual larynx, but it can produce a yodeling sound.",
        "It has been documented that a snail can enter a sleep state for up to three years under certain conditions.",
        "Elephants are the only animals in the animal kingdom that are physically incapable of jumping off the ground.",
        "Rats have been shown to produce a laughter-like sound when tickled, indicating playful behavior and enjoyment.",
        "Interestingly, the heart of a shrimp is located in its head, not in its body as one might expect.",
        "It is possible to hypnotize a frog by placing it on its back and gently stroking its stomach, inducing a trance-like state.",
        "Tigers not only have striped fur, but their skin underneath the fur is also striped, unique to each individual.",
        "The distinct smell of a skunk can be detected by a human from a distance of up to a mile away.",
        "Penguins possess a special organ above their eyes that enables them to convert seawater into fresh water for drinking.",
        "A crocodile is physically unable to stick its tongue out of its mouth due to anatomical constraints.",
        "Butterflies have taste receptors on their feet, allowing them to taste their food by standing on it.",
        "Sea otters often hold hands while they sleep to prevent themselves from drifting apart in the moving water.",
        "The average lifespan of a squirrel, living in the wild, is about nine years, depending on the species.",
        "Giraffes are unique in the animal kingdom because they have no vocal cords to produce sounds.",
        "Bats hold the distinction of being the only mammals capable of sustained flight through the air.",
        "A cat's ear is incredibly flexible, containing 32 muscles that allow for precise control over movement.",
        "A common myth is that a goldfish has a memory span of only three seconds, which is not accurate.",
        "An ostrich's eye is impressively large, so much so that it is bigger than its entire brain.",
        "Starfish, or sea stars, do not have brains in the way many other animals do, navigating their environment differently.",
        "Kangaroos are physically unable to walk backwards due to the structure of their bodies and their large tails.",
        "Ants are incredibly hardworking insects that never sleep, constantly working to maintain and protect their colony.",
        "Owls have a unique eye structure, with tube-shaped eyes that provide a wide range of vision but cannot move in their sockets.",
        "The tongue of a blue whale is so massive that it weighs as much as an adult elephant.",
        "Crocodiles are known for their impressive lifespan, with some individuals living up to 100 years in the wild.",
        "Interestingly, it's possible for a cat to develop an allergy to humans, reacting to their presence with allergic symptoms.",
        "An octopus has a total of nine brains: one central brain and eight peripheral brains located in each of its arms.",
        "Dragonflies are equipped with six legs but are unable to walk, using them instead for landing and holding onto surfaces.",
        "In the seahorse species, it is the male that carries the eggs in a special pouch until they hatch, not the female.",
        "Slugs are equipped with four noses, enabling them to have a highly developed sense of smell.",
        "Rabbits have a wide field of vision, allowing them to see behind themselves without needing to turn their heads.",
        "The fingerprints of a koala are so similar to those of humans that they are virtually indistinguishable, even under scrutiny.",
        "A group of owls is collectively referred to as a parliament, showcasing their wise and distinguished reputation in folklore.",
        "Frogs have the ability to absorb water through their skin, eliminating the need for them to drink water in the traditional sense.",
        "Elephants have developed a specific alarm call that specifically means 'human', alerting others to the presence of humans nearby.",
        "Certain species of earthworms are equipped with as many as 10 hearts, allowing for efficient circulation within their bodies.",
        "A hummingbird weighs so little that it is actually less than the weight of a single penny.",
        "An elephant's sense of smell is so keen that it can detect water sources up to 3 miles away.",
        "A cockroach can survive for several weeks without its head, eventually dying from the inability to drink water.",
        "Ducks are equipped with three eyelids on each eye: one for blinking, one for sleeping, and a third to protect the eye underwater.",
        "A bee is capable of flying faster than a turkey, showcasing the remarkable speed and agility of these small insects.",
        "A tarantula spider has the remarkable ability to survive for more than two years without consuming any food.",
        "Horses and cows have the ability to sleep while standing up, thanks to a special mechanism in their legs.",
        "Gorillas, sharing 98% of their DNA with humans, can catch human colds and other illnesses.",
        "A newborn kangaroo is incredibly small at birth, about the size of a lima bean, before it grows in the mother's pouch.",
        "Bats are the only mammals endowed with the capability of sustained flight, making them unique in the mammalian world.",
        "The leg bones of a bat are so thin and lightweight that no bat is capable of walking on them.",
        "Some male songbirds are known to sing more than 2,000 times each day, especially during the mating season to attract females.",
        "Antarctica is the only continent on Earth that is completely devoid of reptiles and snakes due to its cold climate.",
        "An elephant's skin is incredibly thick, about an inch, providing protection against environmental hazards and predators.",
        "Chimpanzees have the cognitive ability to learn to recognize themselves in a mirror, demonstrating self-awareness.",
        "Canaries were once regularly used in coal mining as an early warning system to detect toxic gases.",
        "A single elephant tooth can weigh as much as 9 pounds, reflecting the large size and herbivorous diet of these animals.",
        "The blood of mammals is red due to hemoglobin, insects have yellow blood, and the blood of lobsters is blue.",
        "A group of frogs is collectively known as an army, highlighting their often large and noisy gatherings.",
        "Some lions in the wild engage in mating behavior more than 50 times a day during the breeding season.",
        "Ostriches can achieve faster speeds than horses, making them the fastest two-legged animals in the world.",
        "Albatrosses have the remarkable ability to sleep while flying, utilizing thermal currents to stay aloft without effort.",
        "Worms communicate with each other by snuggling, which is a form of interaction in their underground environments.",
        "The seahorse is the slowest fish, moving through the water at about 0.01 miles per hour with a delicate grace.",
        "Snails have the remarkable ability to regenerate a lost eye, showcasing their regenerative capabilities.",
        "Hummingbirds are the only birds capable of flying backwards.",
        "The pistol shrimp can create a bubble hot enough to rival the sun's surface temperature and loud enough to stun prey.",
        "Turritopsis dohrnii, a species of jellyfish, is considered biologically immortal. It can revert back to its polyp stage after reaching maturity.",
        "Lyrebirds can mimic almost any sound they hear, including chainsaws, car alarms, and camera shutters.",
        "The mantis shrimp has one of the fastest and most powerful punches in nature, capable of breaking aquarium glass.",
        "Echidnas, along with the platypus, are the only egg-laying mammals known as monotremes.",
        "The vampire bat is the only mammal that feeds entirely on blood.",
        "Wombats produce cube-shaped feces. This unusual shape prevents the feces from rolling away, marking territory more effectively.",
        "The axolotl can regenerate not just its limbs but also its heart and parts of its brain and spine.",
        "Kakapos are flightless parrots known for their nocturnal behavior and are considered one of the world's longest-living birds.",
        "The Greenland shark has the longest known lifespan of all vertebrate species, estimated to be up to 400 years.",
        "Cheetahs do not roar like other big cats; they purr.",
        "The peacock mantis shrimp's eyes are so complex they can perceive both polarized light and multispectral images.",
        "Sloths move so slowly that algae can grow on their fur, which acts as camouflage.",
        "The tongue of the blue whale is so large that fifty people can stand on it.",
        "Electric eels can produce electric shocks of up to 600 volts to stun prey or defend themselves.",
        "The peregrine falcon is the fastest bird, reaching speeds over 240 mph during its hunting stoop.",
        "Narwhals change color as they age: they are blue-gray at birth, turn white as they get older.",
        "African elephants have larger ears than Asian elephants, which they use to radiate excess heat.",
        "The honey badger is one of the most fearless animals in the world, known to attack animals much larger than itself.",
        "Sea cucumbers can expel their internal organs to fend off predators and then regenerate them.",
        "Armadillos are capable of holding their breath for up to six minutes, allowing them to walk underwater across the bottoms of streams and ponds.",
        "Tardigrades, also known as water bears, can survive extreme conditions, including the vacuum of space.",
    ];

    
    // different types of keycap plastic, tape mode, tempest tape mode, thock isn't one component but everything together,
    const keyboardFacts: string[] = [
        "Mechanical keyboards use individual mechanical switches for each key.",
        "The first mechanical keyboards were developed in the early 1970s.",
        "Cherry MX switches are among the most popular mechanical switches and come in various colors indicating their tactile feel and actuation force.",
        "Mechanical keyboards are often praised for their durability, typically lasting for tens of millions of key presses.",
        "Customizable keycaps allow for personalization of mechanical keyboards, with options ranging from different materials to unique designs.",
        "Mechanical keyboards can be significantly louder than their membrane counterparts, with clicky switches producing a distinctive sound.",
        "The actuation point in a mechanical switch is the distance at which a keypress is registered, which can vary between switch types.",
        "Many mechanical keyboards offer N-Key Rollover (NKRO) allowing multiple keys to be registered simultaneously.",
        "The IBM Model M, released in 1984, is one of the most iconic and sought-after mechanical keyboards.",
        "Key switch actuation force is measured in centinewtons or grams, indicating the amount of force needed to press the key.",
        "Lubricating switches and stabilizers can significantly reduce noise and improve the feel of a mechanical keyboard.",
        "The term 'keycap profile' refers to the shape and height of the keycaps, which can affect typing comfort and speed.",
        "Enthusiasts sometimes use o-rings under keycaps to dampen the sound of bottoming out keys.",
        "Hot-swappable mechanical keyboards allow users to change switches without soldering, making customization easier.",
        "Wireless mechanical keyboards are available, combining the reliability of mechanical switches with the convenience of wireless connectivity.",
        "The resurgence of mechanical keyboards in popularity has led to the development of new switch types and technologies beyond traditional models.",
    ];

    const data = useMemo(() => {
        if (scholarType === "vocab") {
            return vocabDefinitions;
        } else if (scholarType === "animals") {
            return animalFacts;
        } else if (scholarType === "keyboards") {
            return keyboardFacts;
        } else {
            console.error("Invalid scholar type");
            return [];
        }
    }, [scholarType]);

    useEffect(() => {
        const randomIndex = Math.floor(Math.random() * data.length);
        const randomDefinition = data[randomIndex];
        if (randomDefinition) {
            const wordsArray = randomDefinition.split(" ");
            setPrompt(wordsArray);
        }
    }, [data, setPrompt]);

    return <></>;
}
