import { useEffect, useMemo } from "react";

interface ScholarGeneratorProps {
    setPrompt: (newPrompt: string[]) => void;
    scholarType: string;
}

export default function ScholarGenerator({
    scholarType,
    setPrompt,
}: ScholarGeneratorProps) {
    // depending on the scholar type we want to set our prompt (which is an array of strings) to a sentence split by every space. "we want punctuatoin here"

    const vocabDefinitions: string[] = [
        "Aberrate: to deviate from the normal way. His behavior aberrated from the group norms.",
        "Acuity: sharpness or keenness of thought, vision, or hearing. Her visual acuity helped her become an excellent photographer.",
        "Advocacy: public support for or recommendation of a particular cause or policy. She's known for her strong advocacy for animal rights.",
        "Affable: friendly, good-natured, or easy to talk to. His affable nature makes him very approachable.",
        "Aggregate: a whole formed by combining several elements. They aggregated the data from all sources into one report.",
        "Amalgamate: to merge into a single body. He amalgamated his company with another.",
        "Amenity: a desirable or useful feature or facility of a building or place. The hotel offers many amenities such as a pool and a gym.",
        "Analogical: relating to or based on analogy. His explanation was analogical, comparing the cell to a factory.",
        "Animosity: strong hostility. There's a deep animosity between the two competing factions.",
        "Aperture: an opening, hole, or gap. The aperture of the lens was adjusted to let in more light.",
        "Apprise: inform or tell (someone). I must apprise you of the changes to the schedule.",
        "Aptitude: a natural ability to do something. She has an aptitude for languages.",
        "Arduous: involving or requiring strenuous effort; difficult and tiring. The climb was arduous, but the view was worth it.",
        "Assiduous: showing great care and perseverance. She was assiduous in her studies, aiming for the top of her class.",
        "Astringent: causing the contraction of body tissues, typically used to protect the skin. The astringent lotion helped clear her skin.",
        "Attenuate: reduce the force, effect, or value of. They attempted to attenuate the conflict through mediation.",
        "Augment: make (something) greater by adding to it; increase. He augmented his income by freelancing in his spare time.",
        "Austere: severe or strict in manner, attitude, or appearance. His austere demeanor was intimidating to the new staff.",
        "Abyssal: relating to or denoting the depths of the ocean. The abyssal zone is home to unique species adapted to its dark conditions.",
        "Accolade: an award or privilege granted as a special honor. She received an accolade for her contributions to science.",
        "Acumen: the ability to make good judgments and quick decisions. His business acumen is respected in the industry.",
        "Adjudicate: make a formal judgment or decision about a problem or disputed matter. The committee will adjudicate the case next week.",
        "Aeonian: lasting for an immeasurably or indefinitely long period of time. Their love was described as aeonian, enduring through all trials.",
        "Affinity: a spontaneous or natural liking or sympathy for someone or something. He has an affinity for classical music.",
        "Aggrandize: increase the power, status, or wealth of. He sought to aggrandize himself at the expense of others.",
        "Alacrity: brisk and cheerful readiness. She accepted the invitation with alacrity.",
        "Alchemy: the medieval forerunner of chemistry, concerned with the transmutation of matter. The alchemist attempted to change lead into gold through alchemy.",
        "Allay: diminish or put at rest (fear, suspicion, or worry). The report served to allay the public's fears.",
        "Allegory: a story, poem, or picture that can be interpreted to reveal a hidden meaning, typically a moral or political one. His book is an allegory for the perils of greed.",
        "Ameliorate: make (something bad or unsatisfactory) better. They took measures to ameliorate the effects of pollution.",
        "Amorphous: without a clearly defined shape or form. The amorphous blob puzzled the scientists.",
        "Anachronism: a thing belonging or appropriate to a period other than that in which it exists. The sword is an anachronism in modern warfare.",
        "Anodyne: not likely to provoke dissent or offense; inoffensive, often deliberately so. The remarks were deliberately anodyne to avoid controversy.",
        "Anathema: something or someone that one vehemently dislikes. Censorship is anathema to democratic societies.",
        "Anecdotal: (of information) not necessarily true or reliable, because based on personal accounts rather than facts or research. Most evidence of alien encounters is anecdotal.",
        "Angst: a feeling of deep anxiety or dread, typically an unfocused one about the human condition or the state of the world in general. Teenage angst can be difficult to manage.",
        "Animus: hostility or ill feeling. There was a clear animus between the two rivals.",
        "Annex: add (territory) to one's own territory by appropriation. The country annexed the neighboring island.",
        "Anomaly: something that deviates from what is standard, normal, or expected. There was an anomaly in the data that suggested a new phenomenon.",
        "Antediluvian: ridiculously old-fashioned. His antediluvian views on technology were not well-received at the conference.",
        "Antipathy: a deep-seated feeling of dislike; aversion. Her antipathy towards the group was obvious to everyone.",
        "Apathy: lack of interest, enthusiasm, or concern. Widespread apathy among voters led to a very low turnout on election day.",
        "Aphorism: a pithy observation that contains a general truth. 'If it ain't broke, don't fix it' is a popular aphorism.",
        "Apocryphal: (of a story or statement) of doubtful authenticity, although widely circulated as being true. The tale of his success was apocryphal and embellished by many retellings.",
        "Apostate: a person who renounces a religious or political belief or principle. The apostate was shunned by his community for his change in beliefs.",
        "Apotheosis: the highest point in the development of something; culmination or climax. His election as president was the apotheosis of his political career.",
        "Arcane: understood by few; mysterious or secret. She specialized in arcane legal documents that few could interpret.",
        "Ascetic: characterized by or suggesting the practice of severe self-discipline and abstention from all forms of indulgence, typically for religious reasons. His ascetic lifestyle included fasting and long periods of meditation.",
        "Aspersion: an attack on the reputation or integrity of someone or something. He cast aspersions on his competitor's honesty.",
        "Assuage: make (an unpleasant feeling) less intense. The letter assuaged the fears of most members.",
        "Astral: relating to or resembling the stars. She had an astral vision while meditating under the night sky.",
        "Astringent: sharp or severe in manner or style. His astringent remarks left everyone feeling uneasy.",
        "Asunder: apart; divided. Their once close friendship had fallen asunder over the years.",
        "Asylum: the protection granted by a nation to someone who has left their native country as a political refugee. She sought asylum in the embassy after fleeing her home country.",
        "Atrophy: (of body tissue or an organ) waste away, typically due to the degeneration of cells. The muscles can atrophy when not used regularly.",
        "Audacity: the willingness to take bold risks. Her audacity came as a shock to the more conservative board members.",
        "Augury: a sign of what will happen in the future; an omen. They took the sudden eclipse as an augury of coming change.",
        "Aureate: golden or brilliant. The aureate sunlight bathed the room in a warm glow.",
        "Auroral: pertaining to or resembling the dawn; rosy. The sky had an auroral blush this morning.",
        "Auspicious: conducive to success; favorable. It was an auspicious start to their business venture.",
        "Autocrat: a ruler who has absolute power. Living under an autocrat meant they had little freedom.",
        "Autonomy: the right or condition of self-government. The region demanded greater autonomy from the central government.",
        "Avarice: extreme greed for wealth or material gain. His decisions were driven by pure avarice.",
        "Aver: state or assert to be the case. He averred that he was present at the scene.",
        "Avow: assert or confess openly. He avowed his commitment to the cause in front of the crowd.",
        
    ];

    const animalFacts: string[] = [
        "The tongue of a blue whale is as heavy as an adult elephant.",

        "A cockroach can live several weeks with its head cut off.",
        "It takes a sloth two weeks to digest its food.",

        "Nearly three percent of the ice in Antarctic glaciers is penguin urine.",
        "A cow gives nearly 200,000 glasses of milk in her lifetime.",
        "During World War II, Americans tried to train bats to drop bombs.",

        "The horn of a rhinoceros is made from compacted hair rather than bone or another substance.",
        "Polar bears are nearly undetectable by infrared cameras, due to their transparent fur.",
        "Sharks have been around for more than 400 million years.",
        "Giraffes have black tongues to prevent sunburn while eating in the hot sun.",
        "In terms of weight, the largest organ in birds is their feathers.",
        "Seahorses mate for life, and when they travel, they hold each other's tails.",
        "The slowest fish is the seahorse, which moves along at about 0.01 mph.",
        "Most reptiles lay eggs, but some snakes give birth to live young.",
        "Elephants can hear one another's trumpeting calls up to 5 miles away.",
        "A rhinoceros beetle can lift objects 850 times its own weight.",
        "The sailfish is considered the fastest fish in the ocean, capable of swimming up to 68 miles per hour.",
        "Giraffes only need 5 to 30 minutes of sleep in a 24-hour period.",
        "The age of a lobster can be determined by counting its rings, similar to a tree.",
        "Some species of frogs have the incredible ability to freeze without dying, surviving harsh winter conditions.",

        "Cows have been observed to form close friendships and can become stressed if they are separated from their best friends.",
        "Dolphins are known to assign names to each other and can specifically call out to one another using those names.",
        "The Basenji dog is uniquely known as the 'barkless dog' due to its unusual larynx, but it can produce a yodeling sound.",
        "It has been documented that a snail can enter a sleep state for up to three years under certain conditions.",
        "Elephants are the only animals in the animal kingdom that are physically incapable of jumping off the ground.",
        "Rats have been shown to produce a laughter-like sound when tickled, indicating playful behavior and enjoyment.",
        "Interestingly, the heart of a shrimp is located in its head, not in its body as one might expect.",
        "A rhinoceros' horn is not bone but is actually made of tightly packed, keratin fibers, similar to human hair.",
        "It is possible to hypnotize a frog by placing it on its back and gently stroking its stomach, inducing a trance-like state.",
        "Tigers not only have striped fur, but their skin underneath the fur is also striped, unique to each individual.",
        "The distinct smell of a skunk can be detected by a human from a distance of up to a mile away.",
        "Penguins possess a special organ above their eyes that enables them to convert seawater into fresh water for drinking.",
        "A crocodile is physically unable to stick its tongue out of its mouth due to anatomical constraints.",
        "Butterflies have taste receptors on their feet, allowing them to taste their food by standing on it.",
        "Sea otters often hold hands while they sleep to prevent themselves from drifting apart in the moving water.",
        "The average lifespan of a squirrel, living in the wild, is about nine years, depending on the species.",
        "Giraffes are unique in the animal kingdom because they have no vocal cords to produce sounds.",
        "Bats hold the distinction of being the only mammals capable of sustained flight through the air.",
        "A cat's ear is incredibly flexible, containing 32 muscles that allow for precise control over movement.",
        "A common myth is that a goldfish has a memory span of only three seconds, which is not accurate.",
        "An ostrich's eye is impressively large, so much so that it is bigger than its entire brain.",
        "Starfish, or sea stars, do not have brains in the way many other animals do, navigating their environment differently.",
        "Kangaroos are physically unable to walk backwards due to the structure of their bodies and their large tails.",
        "Ants are incredibly hardworking insects that never sleep, constantly working to maintain and protect their colony.",
        "Owls have a unique eye structure, with tube-shaped eyes that provide a wide range of vision but cannot move in their sockets.",
        "A 'mob', 'troop', or 'court' are all terms used to describe a group of kangaroos when they gather together.",
        "Deer are unable to digest hay properly due to the specific makeup of their digestive systems, requiring other forms of vegetation.",
        "The tongue of a blue whale is so massive that it weighs as much as an adult elephant.",
        "Crocodiles are known for their impressive lifespan, with some individuals living up to 100 years in the wild.",
        "A 'jiffy' is officially defined as an actual unit of time, equating to 1/100th of a second.",
        "Interestingly, it's possible for a cat to develop an allergy to humans, reacting to their presence with allergic symptoms.",
        "An octopus has a total of nine brains: one central brain and eight peripheral brains located in each of its arms.",
        "Dragonflies are equipped with six legs but are unable to walk, using them instead for landing and holding onto surfaces.",
        "In the seahorse species, it is the male that carries the eggs in a special pouch until they hatch, not the female.",
        "Slugs are equipped with four noses, enabling them to have a highly developed sense of smell.",
        "Rabbits have a wide field of vision, allowing them to see behind themselves without needing to turn their heads.",
        "The fingerprints of a koala are so similar to those of humans that they are virtually indistinguishable, even under scrutiny.",
        "A group of owls is collectively referred to as a parliament, showcasing their wise and distinguished reputation in folklore.",
        "Frogs have the ability to absorb water through their skin, eliminating the need for them to drink water in the traditional sense.",
        "Elephants have developed a specific alarm call that specifically means 'human', alerting others to the presence of humans nearby.",
        "Certain species of earthworms are equipped with as many as 10 hearts, allowing for efficient circulation within their bodies.",
        "A hummingbird weighs so little that it is actually less than the weight of a single penny.",
        "An elephant's sense of smell is so keen that it can detect water sources up to 3 miles away.",
        "The average lifespan of a chicken can range from five to ten years, depending on the breed and conditions.",
        "A queen bee, the leader of the bee colony, can live for up to five years, overseeing the hive.",
        "A cockroach can survive for several weeks without its head, eventually dying from the inability to drink water.",
        "Ducks are equipped with three eyelids on each eye: one for blinking, one for sleeping, and a third to protect the eye underwater.",
        "A group of jellyfish is uniquely referred to as a smack, highlighting the distinct collective behavior of these marine animals.",
        "A bee is capable of flying faster than a turkey, showcasing the remarkable speed and agility of these small insects.",
        "A tarantula spider has the remarkable ability to survive for more than two years without consuming any food.",
        "Horses and cows have the ability to sleep while standing up, thanks to a special mechanism in their legs.",
        "Gorillas, sharing 98% of their DNA with humans, can catch human colds and other illnesses.",
        "A newborn kangaroo is incredibly small at birth, about the size of a lima bean, before it grows in the mother's pouch.",
        "The average weight of a fox is around 14 pounds, varying slightly among different species of foxes.",
        "Bats are the only mammals endowed with the capability of sustained flight, making them unique in the mammalian world.",
        "The leg bones of a bat are so thin and lightweight that no bat is capable of walking on them.",
        "Some male songbirds are known to sing more than 2,000 times each day, especially during the mating season to attract females.",
        "Antarctica is the only continent on Earth that is completely devoid of reptiles and snakes due to its cold climate.",
        "An elephant's skin is incredibly thick, about an inch, providing protection against environmental hazards and predators.",
        "Chimpanzees have the cognitive ability to learn to recognize themselves in a mirror, demonstrating self-awareness.",
        "Most elephants weigh less than the tongue of a blue whale, emphasizing the sheer size of these marine mammals.",
        "It takes a sloth up to two weeks to digest its food, reflecting its slow metabolism and lifestyle.",
        "Nearly three percent of the ice in Antarctic glaciers is composed of penguin urine, a testament to the large penguin populations.",
        "A single cow is capable of producing nearly 200,000 glasses of milk in her lifetime, contributing significantly to dairy production.",
        "A housefly hums in the musical key of F, one of the interesting aspects of this common insect.",
        "During World War II, Americans experimented with training bats to carry small bombs, although the project was eventually abandoned.",
        "Canaries were once regularly used in coal mining as an early warning system to detect toxic gases.",
        "A single elephant tooth can weigh as much as 9 pounds, reflecting the large size and herbivorous diet of these animals.",
        "The blood of mammals is red due to hemoglobin, insects have yellow blood, and the blood of lobsters is blue.",
        "A group of frogs is collectively known as an army, highlighting their often large and noisy gatherings.",
        "The unique smell of a skunk, which can be detected by humans from a mile away, is a defense mechanism against predators.",
        "Some lions in the wild engage in mating behavior more than 50 times a day during the breeding season.",
        "Butterflies are capable of seeing a range of colors including red, green, and yellow, aiding in their search for nectar.",
        "Ladybugs are beneficial insects, capable of consuming up to 5,000 aphids in their lifetime, helping to control pest populations.",
        "Ostriches can achieve faster speeds than horses, making them the fastest two-legged animals in the world.",
        "Albatrosses have the remarkable ability to sleep while flying, utilizing thermal currents to stay aloft without effort.",
        "The horn of a rhinoceros is made from compacted hair-like fibers, rather than bone or another hard substance.",
        "Polar bears have transparent fur that is nearly undetectable by infrared cameras, providing excellent insulation in cold environments.",
        "Dogs possess about 1,700 taste buds on their tongues, allowing them to taste a variety of flavors.",
        "Sharks have been inhabiting Earth's oceans for more than 400 million years, predating the dinosaurs.",
        "Giraffes have tongues that are black in color, which helps prevent sunburn while they feed on leaves in the hot sun.",
        "A group of unicorns, if they were real, would be whimsically called a blessing, according to folklore.",
        "Worms communicate with each other by snuggling, which is a form of interaction in their underground environments.",
        "Baby porcupines, known as porcupettes, are born with soft quills that harden a few days after birth to provide protection.",
        "Interestingly, a shrimp's heart is located in its head, which is an unusual feature among animals.",
        "In terms of weight, the largest organ in birds is their feathers, crucial for flight and insulation.",
        "Seahorses are monogamous and mate for life, often traveling in pairs while holding each other's tails.",
        "The seahorse is the slowest fish, moving through the water at about 0.01 miles per hour with a delicate grace.",
        "Snails have the remarkable ability to regenerate a lost eye, showcasing their regenerative capabilities.",
        "Alligators can have a lifespan of up to 50 years in the wild, making them long-lived reptiles.",
        "A group of flamingos is called a flamboyance, reflecting their vibrant colors and social nature.",
        "Most reptiles lay eggs, but some species of snakes give birth to live young, adapting to their environments.",
        "Hummingbirds are the only birds capable of flying backwards, demonstrating incredible agility in the air.",
        "Elephants can communicate with one another using trumpeting calls that can be heard up to 5 miles away, facilitating long-distance communication.",

        "The pistol shrimp can create a bubble hot enough to rival the sun's surface temperature and loud enough to stun prey.",
        "Turritopsis dohrnii, a species of jellyfish, is considered biologically immortal. It can revert back to its polyp stage after reaching maturity.",
        "Lyrebirds can mimic almost any sound they hear, including chainsaws, car alarms, and camera shutters.",
        "The mantis shrimp has one of the fastest and most powerful punches in nature, capable of breaking aquarium glass.",
        "Parrotfish sleep in a protective cocoon made of their own mucus to hide their scent from predators.",
        "The Saiga antelope has an extremely large and flexible nose that helps filter out dust and regulate its blood temperature.",
        "Echidnas, along with the platypus, are the only egg-laying mammals known as monotremes.",
        "The vampire bat is the only mammal that feeds entirely on blood.",
        "Wombats produce cube-shaped feces. This unusual shape prevents the feces from rolling away, marking territory more effectively.",
        "The axolotl can regenerate not just its limbs but also its heart and parts of its brain and spine.",
        "Kakapos are flightless parrots known for their nocturnal behavior and are considered one of the world's longest-living birds.",
        "The Greenland shark has the longest known lifespan of all vertebrate species, estimated to be up to 400 years.",
        "Cheetahs do not roar like other big cats; they purr.",
        "The peacock mantis shrimp's eyes are so complex they can perceive both polarized light and multispectral images.",
        "Sloths move so slowly that algae can grow on their fur, which acts as camouflage.",
        "The tongue of the blue whale is so large that fifty people can stand on it.",
        "Electric eels can produce electric shocks of up to 600 volts to stun prey or defend themselves.",
        "The hoatzin, a tropical bird found in the Amazon, is known for its unique digestive system that ferments vegetation like a cow's stomach.",
        "The peregrine falcon is the fastest bird, reaching speeds over 240 mph (386 km/h) during its hunting stoop (high-speed dive).",
        "Narwhals change color as they age: they are blue-gray at birth, turn white as they get older.",
        "African elephants have larger ears than Asian elephants, which they use to radiate excess heat.",
        "The okapi, a relative of the giraffe, has zebra-like stripes on its legs but lives in the dense rainforests of the Congo.",
        "The honey badger is one of the most fearless animals in the world, known to attack animals much larger than itself.",
        "The male bowerbird builds intricate structures, decorated with brightly colored objects, to attract mates.",
        "Sea cucumbers can expel their internal organs to fend off predators and then regenerate them.",
        "The Malayan colugo is considered one of the best gliders among all gliding mammals, able to glide over 200 meters between trees.",
        "Armadillos are capable of holding their breath for up to six minutes, allowing them to walk underwater across the bottoms of streams and ponds.",
        "The quokka is known as the happiest animal in the world due to its smile-like facial expression.",
        "Fruit bats are essential for pollination and seed dispersal in tropical and subtropical environments.",
        "The male frigatebird inflates a red throat pouch to attract females during mating season.",
        "Tardigrades, also known as water bears, can survive extreme conditions, including the vacuum of space.",
        "The cassowary is considered one of the most dangerous birds due to its powerful kick and sharp claws.",
        "Kiwi birds are blind, relying on their other senses to navigate and find food.",
        "The anglerfish's female has a luminous lure used to attract prey in the deep, dark waters of the ocean.",
    ];

    const keyboardFacts: string[] = [
        "Mechanical keyboards use individual mechanical switches for each key.",
        "The first mechanical keyboards were developed in the early 1970s.",
        "Cherry MX switches are among the most popular mechanical switches and come in various colors indicating their tactile feel and actuation force.",
        "Mechanical keyboards are often praised for their durability, typically lasting for tens of millions of key presses.",
        "Customizable keycaps allow for personalization of mechanical keyboards, with options ranging from different materials to unique designs.",
        "Mechanical keyboards can be significantly louder than their membrane counterparts, with clicky switches producing a distinctive sound.",
        "The actuation point in a mechanical switch is the distance at which a keypress is registered, which can vary between switch types.",
        "Many mechanical keyboards offer N-Key Rollover (NKRO) allowing multiple keys to be registered simultaneously.",
        "The IBM Model M, released in 1984, is one of the most iconic and sought-after mechanical keyboards.",
        "Key switch actuation force is measured in centinewtons (cN) or grams, indicating the amount of force needed to press the key.",
        "Mechanical keyboards are favored in typing and gaming for their precise and consistent key feel.",
        "The custom mechanical keyboard community often shares designs for printed circuit boards (PCBs), cases, and firmware, promoting DIY builds.",
        "Lubricating switches and stabilizers can significantly reduce noise and improve the feel of a mechanical keyboard.",
        "The term 'keycap profile' refers to the shape and height of the keycaps, which can affect typing comfort and speed.",
        "Enthusiasts sometimes use o-rings under keycaps to dampen the sound of bottoming out keys.",
        "Hot-swappable mechanical keyboards allow users to change switches without soldering, making customization easier.",
        "Wireless mechanical keyboards are available, combining the reliability of mechanical switches with the convenience of wireless connectivity.",
        "Programmable mechanical keyboards enable users to remap keys and configure multiple layers for shortcuts and macros.",
        "The cost of mechanical keyboards can vary widely, from affordable models to expensive custom setups exceeding several hundred dollars.",
        "Mechanical keyboard meetups and conventions allow enthusiasts to share their custom builds, new designs, and innovations in the community.",
        "The resurgence of mechanical keyboards in popularity has led to the development of new switch types and technologies beyond traditional models.",
    ];

    const data = useMemo(() => {
        if (scholarType === "Vocab") {
            return vocabDefinitions;
        } else if (scholarType === "Animal") {
            return animalFacts;
        } else {
            console.error("Invalid scholar type");
            return [];
        }
    }, [scholarType]);

    useEffect(() => {
        const randomIndex = Math.floor(Math.random() * data.length);
        const randomDefinition = data[randomIndex];
        if (randomDefinition) {
            const wordsArray = randomDefinition.split(" ");
            setPrompt(wordsArray);
        }
    }, [data, setPrompt]);

    return <></>;
}
