import { useEffect } from "react";

interface SentenceGeneratorProps {
    gameLength: number;
    setPrompt: (prompt: string[]) => void;
}

export default function SentenceGenerator({
    gameLength,
    setPrompt,
}: SentenceGeneratorProps) {
    // todo prevent repeat words
    //
    const wordBank: string[] = [
        "about",
        "able",
        "across",
        "add",
        "after",
        "again",
        "against",
        "air",
        "all",
        "along",
        "almost",
        "also",
        "always",
        "animal",
        "answer",
        "appear",
        "area",
        "around",
        "ask",
        "away",
        "back",
        "because",
        "become",
        "been",
        "before",
        "began",
        "begin",
        "behind",
        "below",
        "best",
        "better",
        "between",
        "big",
        "birds",
        "black",
        "body",
        "book",
        "both",
        "boy",
        "but",
        "call",
        "came",
        "can",
        "car",
        "carry",
        "center",
        "certain",
        "change",
        "children",
        "city",
        "clear",
        "close",
        "cold",
        "come",
        "complete",
        "contain",
        "correct",
        "could",
        "country",
        "covered",
        "cry",
        "cut",
        "dark",
        "day",
        "develop",
        "different",
        "did",
        "didn't",
        "don't",
        "door",
        "down",
        "drive",
        "during",
        "each",
        "early",
        "earth",
        "eat",
        "easy",
        "end",
        "enough",
        "even",
        "ever",
        "every",
        "example",
        "face",
        "fact",
        "fall",
        "family",
        "far",
        "farm",
        "fast",
        "father",
        "few",
        "field",
        "figure",
        "find",
        "fine",
        "first",
        "fish",
        "five",
        "fly",
        "follow",
        "food",
        "for",
        "found",
        "four",
        "friends",
        "from",
        "front",
        "get",
        "give",
        "go",
        "good",
        "got",
        "govern",
        "great",
        "green",
        "ground",
        "group",
        "grow",
        "had",
        "hand",
        "happened",
        "hard",
        "has",
        "have",
        "hear",
        "her",
        "here",
        "high",
        "him",
        "his",
        "hold",
        "home",
        "horse",
        "hour",
        "hours",
        "house",
        "how",
        "however",
        "hundred",
        "important",
        "into",
        "its",
        "just",
        "keep",
        "kind",
        "knew",
        "know",
        "land",
        "large",
        "last",
        "later",
        "lay",
        "lead",
        "learn",
        "leave",
        "left",
        "less",
        "let",
        "letter",
        "life",
        "light",
        "like",
        "line",
        "list",
        "listen",
        "little",
        "live",
        "long",
        "look",
        "low",
        "machine",
        "made",
        "make",
        "man",
        "many",
        "map",
        "mark",
        "may",
        "me",
        "mean",
        "measure",
        "men",
        "might",
        "mile",
        "mind",
        "minute",
        "miss",
        "money",
        "more",
        "morning",
        "most",
        "mother",
        "mountain",
        "move",
        "much",
        "music",
        "must",
        "my",
        "name",
        "need",
        "never",
        "new",
        "next",
        "night",
        "no",
        "noun",
        "now",
        "number",
        "off",
        "often",
        "oil",
        "old",
        "on",
        "once",
        "one",
        "only",
        "open",
        "order",
        "other",
        "our",
        "out",
        "over",
        "own",
        "page",
        "paper",
        "part",
        "pattern",
        "people",
        "person",
        "piece",
        "place",
        "plant",
        "play",
        "point",
        "pound",
        "power",
        "produce",
        "products",
        "problem",
        "put",
        "questions",
        "quick",
        "rain",
        "reach",
        "read",
        "real",
        "red",
        "remember",
        "rest",
        "right",
        "river",
        "road",
        "rock",
        "room",
        "rule",
        "run",
        "said",
        "same",
        "saw",
        "say",
        "school",
        "sea",
        "second",
        "see",
        "seem",
        "sentence",
        "set",
        "several",
        "she",
        "ship",
        "short",
        "should",
        "show",
        "side",
        "simple",
        "since",
        "sing",
        "six",
        "slow",
        "small",
        "so",
        "some",
        "something",
        "sometimes",
        "song",
        "soon",
        "sound",
        "space",
        "special",
        "spell",
        "stand",
        "start",
        "state",
        "stay",
        "step",
        "still",
        "stood",
        "stop",
        "story",
        "strong",
        "study",
        "such",
        "sun",
        "sure",
        "table",
        "tail",
        "take",
        "talk",
        "teach",
        "tell",
        "ten",
        "than",
        "that",
        "the",
        "their",
        "them",
        "then",
        "there",
        "these",
        "they",
        "thing",
        "think",
        "this",
        "those",
        "thought",
        "three",
        "through",
        "time",
        "today",
        "together",
        "told",
        "took",
        "top",
        "toward",
        "tree",
        "true",
        "try",
        "turn",
        "two",
        "under",
        "unit",
        "until",
        "up",
        "us",
        "use",
        "usually",
        "verb",
        "very",
        "voice",
        "vowel",
        "walk",
        "want",
        "warm",
        "was",
        "water",
        "waves",
        "way",
        "we",
        "week",
        "well",
        "went",
        "were",
        "west",
        "what",
        "when",
        "where",
        "which",
        "white",
        "who",
        "why",
        "will",
        "wind",
        "with",
        "without",
        "word",
        "work",
        "would",
        "write",
        "years",
        "young",
        "your",
    ];

    useEffect(() => {
        const randomWords: string[] = [];
        for (let i = 0; i < gameLength; i++) {
            const randomIndex = Math.floor(Math.random() * wordBank.length);
            const randomWord: string | undefined = wordBank[randomIndex];
            if (randomWord) {
                randomWords.push(randomWord);
            }
        }
        setPrompt(randomWords);
    }, [gameLength, setPrompt]);

    return <></>;
}

// {`
// [
//     "abandon", "ability", "abroad", "absence", "absolute", "abstract", "academy", "accent",
//     "accept", "access", "accident", "account", "accuracy", "accurate", "achieve", "acquire",
//     "action", "active", "activity", "actor", "actress", "adapt", "addition", "address",
//     "adjust", "administer", "admire", "admission", "admit", "adopt", "adventure", "advice",
//     "advise", "affect", "afford", "agency", "agenda", "aggressive", "agreement", "aircraft",
//     "airline", "airport", "alarm", "album", "alcohol", "alert", "algebra", "algorithm",
//     "alike", "alive", "allege", "allow", "alloy", "alphabet", "alter", "alternative",
//     "amateur", "amazing", "ambition", "ambulance", "amend", "among", "amount", "analysis",
//     "ancestor", "ancient", "angle", "angry", "animal", "announce", "annual", "anonymous",
//     "anxiety", "apart", "apology", "appeal", "appearance", "apple", "application", "apply",
//     "appoint", "approach", "approval", "approximate", "archive", "area", "argument", "arise",
//     "arrange", "arrest", "arrival", "arrogant", "artificial", "artist", "aspect", "assault",
//     "assemble", "assert", "assess", "assign", "assist", "assume", "assure", "athlete",
//     "atmosphere", "atom", "attach", "attack", "attempt", "attend", "attention", "attitude",
//     "attorney", "attract", "auction", "audience", "author", "automatic", "autumn", "available",
//     "average", "avoid", "awake", "award", "aware", "awesome", "awkward", "background",
//     "bacteria", "balance", "banish", "banker", "barrier", "basement", "basic", "battery",
//     "battle", "beauty", "because", "become", "before", "begin", "behavior", "belief",
//     "belong", "benefit", "beside", "beyond", "bicycle", "billion", "biology", "blanket",
//     "blessing", "border", "borrow", "bother", "boundary", "branch", "bravery", "breathe",
//     "bridge", "brief", "brilliant", "broadcast", "brother", "budget", "building", "bulletin",
//     "bundle", "burden", "business", "butter", "button", "calculate", "calendar", "campaign",
//     "cancel", "cancer", "candidate", "capable", "capital", "captain", "capture", "careful",
//     "carriage", "carrier", "carve", "casino", "casual", "category", "celebrate", "cemetery",
//     "century", "ceremony", "certain", "chairman", "challenge", "champion", "chance", "change",
//     "channel", "chapter", "charge", "charity", "charlie", "chart", "chase", "cheerful",
//     "chemical", "chicken", "chief", "choice", "choose", "chronic", "circuit", "citizen",
//     "civilian", "clarify", "classic", "climate", "clinic", "clock", "clothing", "cloud",
//     "cluster", "coast", "collapse", "collect", "college", "colony", "combine", "comedy",
//     "comfort", "command", "comment", "commerce", "commission", "commit", "common", "communicate",
//     "companion", "compare", "compete", "complain", "complete", "complex", "compose", "computer",
//     "conceive", "concept", "concern", "concert", "conclude", "concrete", "conduct", "confess",
//     "conflict", "conform", "confront", "confuse", "congress", "connect", "consider", "consist",
//     "consult", "consume", "contact", "contain", "contest", "contract", "contrast", "control",
//     "convert", "convey", "convince", "cooperate", "coordinate", "correct", "corrupt", "costume",
//     "council", "counsel", "count", "counter", "country", "courage", "course", "cousin",
//     "create", "creature", "credit", "cricket", "criminal", "crisis", "critic", "critique",
//     "crucial", "crystal", "culture", "curious", "current", "curtain", "curve", "custom",
//     "damage", "danger", "darkness", "database", "debate", "decade", "decay", "deceive",
//     "decide", "declare", "decline", "decorate", "decrease", "dedicate", "defeat", "defend",
//     "define", "degree", "deliver", "demand", "democracy", "demonstrate", "density", "depart",
//     "depend", "deposit", "describe", "deserve", "design", "desire", "destroy", "detail",
//     "detect", "determine", "develop", "device", "devote", "diagram", "dialogue", "diamond",
//     "differ", "digest", "dignity", "dimension", "dinner", "diploma", "direct", "disaster",
//     "discuss", "disease", "disguise", "dismiss", "display", "dispute", "distance", "distinct",
//     "district", "diverse", "divide", "document", "domestic", "dominate", "donate", "double",
//     "doubt", "dozen", "draft", "drama", "dramatic", "drawback", "dream", "drift",
//     "driver", "dynamic", "eager", "easily", "economy", "education", "effect", "effort",
//     "eighth", "elastic", "election", "elegant", "element", "eliminate", "embarrass", "emerge",
//     "emotion", "emphasis", "empire", "employ", "enable", "enclose", "encounter", "endless",
//     "endorse", "energy", "enforce", "engage", "engine", "enhance", "enlarge", "enormous",
//     "enquiry", "enrich", "ensure", "enter", "enterprise", "entire", "entrance", "envelope",
//     "environment", "episode", "equal", "equation", "equip", "equity", "escape", "essay",
//     "essence", "estate", "estimate", "eternal", "ethnic", "evaluate", "evidence", "evolution",
//     "examine", "example", "exceed", "exchange", "excite", "exclude", "execute", "exercise",
//     "exhibit", "exist", "expand", "expect", "explain", "explode", "explore", "export",
//     "expose", "express", "extend", "extra", "extreme", "fabric", "faculty", "failure",
//     "fairy", "faithful", "famous", "fantasy", "farmer", "fashion", "fatal", "father",
//     "favor", "feature", "federal", "feedback", "festival", "fiction", "figure", "final",
//     "finance", "finish", "firmly", "fitness", "flavor", "flexible", "flourish", "focus",
//     "follow", "forbid", "foreign", "forever", "forgive", "formal", "fortune", "forward",
//     "foster", "fraction", "fragment", "framework", "freedom", "frequent", "friendly", "fright",
//     "frontier", "frustrate", "function", "fundamental", "further", "future", "gallery", "gamble",
//     "garden", "garlic", "garment", "gather", "general", "generate", "genius", "genuine",
//     "gesture", "glance", "global", "glory", "golden", "gossip", "govern", "graduate",
//     "graphic", "gravity", "greatest", "grocery", "guarantee", "guardian", "guidance", "guilty",
//     "guitar", "habit", "hammer", "handful", "harmony", "harvest", "heading", "headline",
//     "health", "heaven", "heavy", "height", "heritage", "hesitate", "hidden", "highlight",
//     "highway", "horizon", "horror", "hostile", "humble", "humor", "hunger", "husband",
//     "identify", "ignore", "illegal", "illness", "imagine", "immense", "immune", "impact",
//     "imply", "impose", "impress", "improve", "incident", "include", "increase", "incredible",
//     "indicate", "indirect", "industry", "infamous", "infant", "influence", "inform", "inherit",
//     "initial", "innocent", "inquiry", "insight", "insist", "inspect", "install", "instance",
//     "instead", "instruct", "insurance", "integrate", "intellect", "intense", "interest", "internal",
//     "interpret", "interval", "intimate", "invade", "invention", "invest", "invite", "involve",
//     "isolate", "issue", "item", "jacket", "jealous", "jewel", "journal", "journey",
//     "justice", "justify", "juvenile", "keen", "keyboard", "kingdom", "kitchen", "knowledge",
//     "labor", "landscape", "language", "laptop", "largely", "laughter", "lawyer", "leader",
//     "leading", "league", "lecture", "legend", "leisure", "liberal", "liberty", "library",
//     "license", "lifestyle", "lifetime", "lightning", "likewise", "limited", "literary", "lively",
//     "location", "logical", "loyal", "luxury", "machine", "magazine", "magnify", "maintain",
//     "majority", "manage", "mandate", "manner", "manual", "manufacturer", "margin", "marriage",
//     "massive", "master", "material", "maximum", "meaning", "measure", "mechanism", "medal",
//     "media", "medical", "medium", "mention", "merchant", "message", "metal", "method",
//     "middle", "migrant", "military", "mineral", "minimal", "minister", "minor", "miracle",
//     "mislead", "missing", "mission", "mistake", "mixture", "mobile", "model", "modern",
//     "modify", "moment", "monitor", "moral", "moreover", "morning", "motion", "motivate",
//     "mountain", "movement", "multiple", "murder", "muscle", "museum", "mutual", "mystery",
//     "myth", "narrow", "nation", "native", "natural", "navigate", "nearby", "necessary",
//     "negotiate", "nervous", "network", "neutral", "nevertheless", "newly", "nightmare", "noble",
//     "nominate", "notable", "nothing", "notice", "notion", "novel", "nuclear", "numerous",
//     "obey", "object", "observe", "obtain", "obvious", "occasion", "occupy", "occur",
//     "ocean", "offense", "offer", "office", "operate", "oppose", "option", "orange",
//     "order", "organic", "origin", "otherwise", "outcome", "outdoor", "outer", "outline",
//     "output", "outrage", "outside", "overall", "overcome", "overlook", "overwhelm", "ownership",
//     "oxygen", "package", "painful", "paint", "panel", "panic", "paper", "parade",
//     "paradox", "parallel", "parent", "parking", "parliament", "partial", "partner", "party",
//     "passage", "passion", "passive", "pastor", "patch", "patent", "patient", "pattern",
//     "pause", "payment", "peaceful", "penalty", "people", "percent", "perfect", "perform",
//     "perhaps", "period", "permanent", "permit", "persist", "person", "persuade", "phase",
//     "phenomenon", "philosophy", "phrase", "physical", "physics", "piano", "picture", "piece",
//     "pilot", "pioneer", "pirate", "pitch", "pizza", "planet", "plant", "plastic",
//     "platform", "player", "pleasure", "plenty", "pocket", "poetry", "police", "policy",
//     "politics", "pollution", "popular", "portion", "portrait", "position", "positive", "possess",
//     "possible", "postpone", "potato", "potential", "poverty", "powder", "practice", "praise",
//     "predict", "prefer", "prepare", "preserve", "president", "press", "pressure", "pretend",
//     "prevent", "previous", "price", "primary", "principle", "print", "prison", "private",
//     "probable", "problem", "proceed", "process", "produce", "product", "professor", "profile",
//     "profit", "progress", "project", "promise", "promote", "proof", "proper", "property",
//     "proposal", "protect", "protest", "provide", "public", "publish", "purchase", "pursue",
//     "puzzle", "quality", "quantity", "quarter", "question", "quickly", "quietly", "radar",
//     "radio", "railroad", "random", "rapid", "rarely", "rather", "reality", "realize",
//     "reason", "rebuild", "recall", "receive", "recent", "recognize", "recommend", "record",
//     "recover", "recruit", "reduce", "refer", "reflect", "reform", "refuse", "regard",
//     "regret", "regular", "reject", "relate", "release", "relevant", "relief", "religion",
//     "remain", "remark", "remind", "remove", "render", "repair", "repeat", "replace",
//     "report", "represent", "reputation", "request", "require", "rescue", "research", "reserve",
//     "resign", "resist", "resolve", "respect", "respond", "rest", "restore", "result",
//     "retain", "retire", "reveal", "review", "revise", "reward", "rhythm", "ridiculous",
//     "rival", "romantic", "rotate", "roughly", "routine", "royal", "sacred", "sacrifice",
//     "salary", "salmon", "sample", "satisfy", "scatter", "scenario", "schedule", "scheme",
//     "scholar", "science", "scratch", "scream", "search", "season", "secret", "section",
//     "secure", "segment", "select", "sensible", "sequence", "serious", "session", "settle",
//     "several", "severe", "shadow", "shake", "shallow", "shelter", "shortage", "shoulder",
//     "shrimp", "signal", "silence", "similar", "sincere", "singer", "single", "sister",
//     "situation", "skillful", "slave", "slight", "slowly", "sodium", "software", "solid",
//     "solution", "somehow", "someone", "sophomore", "sorrow", "source", "space", "spare",
//     "speaker", "specific", "specimen", "spectrum", "spelling", "spirit", "sponsor", "sport",
//     "spread", "spring", "spyware", "square", "stable", "stadium", "staff", "standard",
//     "station", "statue", "status", "steady", "steal", "steam", "stereo", "stomach",
//     "strategy", "stream", "strength", "stress", "strict", "struggle", "student", "studio",
//     "style", "subject", "submit", "substance", "subtract", "succeed", "success", "sudden",
//     "suffer", "suggest", "suitable", "summary", "summer", "summit", "superior", "supply",
//     "support", "suppose", "surface", "surplus", "surprise", "survey", "survival", "suspect",
//     "sustain", "swimming", "symbol", "sympathy", "symptom", "system", "tackle", "talent",
//     "target", "taxi", "teach", "technical", "technique", "technology", "teenager", "television",
//     "temperature", "temporary", "tender", "tension", "terminal", "territory", "terror", "testify",
//     "textbook", "theater", "theme", "therapy", "therefore", "thesis", "thorough", "thought",
//     "threat", "thrive", "through", "together", "tolerate", "tomorrow", "torpedo", "torrent",
//     "tournament", "toward", "toxic", "traffic", "transfer", "transform", "translate", "transport",
//     "travel", "treat", "tremble", "trendy", "tribe", "triumph", "trophy", "trouble",
//     "truly", "trust", "tunnel", "typical", "ultimate", "unable", "unaware", "uncle",
//     "uncover", "undergo", "understand", "undertake", "universe", "unlawful", "unlike", "unlimited",
//     "unusual", "update", "upgrade", "uphold", "upstairs", "urban", "urgent", "usage",
//     "utility", "vacation", "valid", "valuable", "variety", "various", "vehicle", "venture",
//     "verdict", "version", "vessel", "veteran", "victory", "village", "violate", "violent",
//     "virtual", "virus", "vision", "visual", "vital", "volcano", "volunteer", "voting",
//     "voyage", "wage", "wander", "warrior", "wealth", "weapons", "weather", "weekend",
//     "welcome", "welfare", "western", "whisper", "whistle", "wholly", "widespread", "willing",
//     "witness", "wonder", "workshop", "worship", "worthy", "wrestle", "writing", "wrong",
//     "yearly", "yellow", "yesterday", "youthful", "zealous", "zebra", "zigzag", "zinc",
//     "zone"
// ];
// `}
